-- Syntax probe: one column only
ALTER TABLE STOKSTAT IN DATABASE DI21PART
  ADD COLUMN SSUNPRC CHAR(9)
    START 11
    TYPE C
    INTERNALNAME SSUNPRC
    INTERNAL TYPECONVERTER CHAR
    CCSID 'Cp1047';

COMMIT;
