-- DI21PART: Remove all non-key fields, leaving only primary/foreign keys per segment.
-- Database: DI21PART (PSB: DFSSAM09)
-- Generated: 2026-07-21
--
-- PARTROOT: drops PARTNAME, PARTDESC (each as a separate ALTER TABLE)
-- STOKSTAT: drops 9 added fields (each as a separate ALTER TABLE)
--           STOCKEY (PK) and PARTKEY (FK -> PARTROOT) are retained.
--
-- Note: IMS JDBC requires COMMIT DDL (not plain COMMIT) for DDL operations.

ALTER TABLE PARTROOT IN DATABASE DI21PART
    DROP COLUMN PARTNAME RESTRICT;

COMMIT DDL;

ALTER TABLE PARTROOT IN DATABASE DI21PART
    DROP COLUMN PARTDESC RESTRICT;

COMMIT DDL;

ALTER TABLE STOKSTAT IN DATABASE DI21PART
    DROP COLUMN SSUNPRC RESTRICT;

COMMIT DDL;

ALTER TABLE STOKSTAT IN DATABASE DI21PART
    DROP COLUMN SSUOMEA RESTRICT;

COMMIT DDL;

ALTER TABLE STOKSTAT IN DATABASE DI21PART
    DROP COLUMN SSSTKDT RESTRICT;

COMMIT DDL;

ALTER TABLE STOKSTAT IN DATABASE DI21PART
    DROP COLUMN SSCREQM RESTRICT;

COMMIT DDL;

ALTER TABLE STOKSTAT IN DATABASE DI21PART
    DROP COLUMN SSUREQM RESTRICT;

COMMIT DDL;

ALTER TABLE STOKSTAT IN DATABASE DI21PART
    DROP COLUMN SSONORD RESTRICT;

COMMIT DDL;

ALTER TABLE STOKSTAT IN DATABASE DI21PART
    DROP COLUMN SSINSTK RESTRICT;

COMMIT DDL;

ALTER TABLE STOKSTAT IN DATABASE DI21PART
    DROP COLUMN SSPLDIS RESTRICT;

COMMIT DDL;

ALTER TABLE STOKSTAT IN DATABASE DI21PART
    DROP COLUMN SSULDIS RESTRICT;

COMMIT DDL;
