-- DI21PART: Add non-key fields from DI00PART source DDL
-- Database: DI21PART (PSB: DFSSAM09)
-- Source:   DI00PART DDL
-- Generated: 2026-07-21
--
-- Segments updated: PARTROOT, STANINFO, STOKSTAT, CYCCOUNT, BACKORDR

-- -------------------------------------------------------------------------
-- PARTROOT: PARTNAME, PARTDESC
-- -------------------------------------------------------------------------
ALTER TABLE PARTROOT IN DATABASE DI21PART
    ADD COLUMN PARTNAME CHAR(12)
        START 18
        TYPE C
        INTERNALNAME PARTNAME
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047';

COMMIT DDL;

ALTER TABLE PARTROOT IN DATABASE DI21PART
    ADD COLUMN PARTDESC CHAR(21)
        START 22
        TYPE C
        INTERNALNAME PARTDESC
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047';

COMMIT DDL;

-- -------------------------------------------------------------------------
-- STANINFO: STANAUDT, STANDATE, STANCHEK
-- -------------------------------------------------------------------------
ALTER TABLE STANINFO IN DATABASE DI21PART
    ADD COLUMN STANAUDT CHAR(4)
        START 3
        TYPE C
        INTERNALNAME STANAUDT
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047';

COMMIT DDL;

ALTER TABLE STANINFO IN DATABASE DI21PART
    ADD COLUMN STANDATE CHAR(10)
        START 7
        TYPE C
        INTERNALNAME STANDATE
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047';

COMMIT DDL;

ALTER TABLE STANINFO IN DATABASE DI21PART
    ADD COLUMN STANCHEK CHAR(69)
        START 17
        TYPE C
        INTERNALNAME STANCHEK
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047';

COMMIT DDL;

-- -------------------------------------------------------------------------
-- STOKSTAT: STOKDATE, STOKEQUP, STOKPERS, STOKLOC
-- -------------------------------------------------------------------------
ALTER TABLE STOKSTAT IN DATABASE DI21PART
    ADD COLUMN STOKDATE CHAR(10)
        START 17
        TYPE C
        INTERNALNAME STOKDATE
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047';

COMMIT DDL;

ALTER TABLE STOKSTAT IN DATABASE DI21PART
    ADD COLUMN STOKEQUP CHAR(24)
        START 27
        TYPE C
        INTERNALNAME STOKEQUP
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047';

COMMIT DDL;

ALTER TABLE STOKSTAT IN DATABASE DI21PART
    ADD COLUMN STOKPERS CHAR(4)
        START 41
        TYPE C
        INTERNALNAME STOKPERS
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047';

COMMIT DDL;

ALTER TABLE STOKSTAT IN DATABASE DI21PART
    ADD COLUMN STOKLOC CHAR(106)
        START 45
        TYPE C
        INTERNALNAME STOKLOC
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047';

COMMIT DDL;

-- -------------------------------------------------------------------------
-- CYCCOUNT: CYCLDATE, CYCLTERM, CYCLRESV
-- -------------------------------------------------------------------------
ALTER TABLE CYCCOUNT IN DATABASE DI21PART
    ADD COLUMN CYCLDATE CHAR(10)
        START 3
        TYPE C
        INTERNALNAME CYCLDATE
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047';

COMMIT DDL;

ALTER TABLE CYCCOUNT IN DATABASE DI21PART
    ADD COLUMN CYCLTERM CHAR(2)
        START 13
        TYPE C
        INTERNALNAME CYCLTERM
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047';

COMMIT DDL;

ALTER TABLE CYCCOUNT IN DATABASE DI21PART
    ADD COLUMN CYCLRESV CHAR(11)
        START 15
        TYPE C
        INTERNALNAME CYCLRESV
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047';

COMMIT DDL;

-- -------------------------------------------------------------------------
-- BACKORDR: BACKDATE, BACKAMT, BACKETA, BACKSUPL
-- -------------------------------------------------------------------------
ALTER TABLE BACKORDR IN DATABASE DI21PART
    ADD COLUMN BACKDATE CHAR(10)
        START 11
        TYPE C
        INTERNALNAME BACKDATE
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047';

COMMIT DDL;

ALTER TABLE BACKORDR IN DATABASE DI21PART
    ADD COLUMN BACKAMT CHAR(4)
        START 21
        TYPE C
        INTERNALNAME BACKAMT
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047';

COMMIT DDL;

ALTER TABLE BACKORDR IN DATABASE DI21PART
    ADD COLUMN BACKETA CHAR(10)
        START 25
        TYPE C
        INTERNALNAME BACKETA
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047';

COMMIT DDL;

ALTER TABLE BACKORDR IN DATABASE DI21PART
    ADD COLUMN BACKSUPL CHAR(41)
        START 35
        TYPE C
        INTERNALNAME BACKSUPL
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047';

COMMIT DDL;
