package com.ibm.ims.jdbcbob;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * IMS DBA Executor — Generated by Bob for Z
 *
 * Persistent DDL execution engine for IMS database administration.
 * Handles two distinct DDL types, auto-detected from file content:
 *
 *   DBD DDL  — CREATE DATABASE / TABLESPACE / TABLE
 *              Full-function (HISAM/HIDAM/HDAM): requires all three statement
 *              types before COMMIT DDL is issued.
 *              DEDB (ACCESS DEDB): no CREATE TABLESPACE — only CREATE DATABASE
 *              + CREATE TABLE are required.
 *              Archives to ddl-output/, logs to ddl-results/.
 *
 *   PSB DDL  — CREATE PROGRAMVIEW
 *              No DBD validation. COMMIT DDL is included in the file itself.
 *              Archives to psb-output/, logs to ddl-results/.
 *
 * COMMIT DDL RULE (DBD only):
 *   COMMIT DDL is issued only after CREATE DATABASE + TABLESPACE + TABLE
 *   have all succeeded in the same session. Never issued on partial success.
 *
 * PSB COMMIT DDL RULE:
 *   COMMIT DDL is the final statement in the PSB DDL file and is executed as-is.
 *   The executor does NOT issue an additional COMMIT DDL after it.
 *
 * Usage:
 *   mvn exec:java -Dexec.mainClass="com.ibm.ims.jdbcbob.IMSDBAExecutor" \
 *     -Dexec.args="CREATE <path_to_ddl_file>"
 *
 * Future operations: ALTER, DROP, VALIDATE
 */
public class IMSDBAExecutor {

    // -------------------------------------------------------------------------
    // Connection constants — sourced from IMSConnectionConfig (single point of change)
    // -------------------------------------------------------------------------
    private static final String HOST     = IMSConnectionConfig.HOST;
    private static final int    PORT     = IMSConnectionConfig.PORT;
    private static final String USER     = IMSConnectionConfig.USER;
    private static final String PASSWORD = IMSConnectionConfig.PASSWORD;
    private static final String DDL_PSB  = IMSConnectionConfig.DDL_PSB;

    // -------------------------------------------------------------------------
    // Output directories
    // -------------------------------------------------------------------------
    private static final String DDL_OUTPUT_DIR  = "../ddl-output";
    private static final String PSB_OUTPUT_DIR  = "../psb-output";
    private static final String DDL_RESULTS_DIR = "../ddl-results";

    // -------------------------------------------------------------------------
    // Entry point
    // -------------------------------------------------------------------------
    public static void main(String[] args) {
        if (args.length < 2) {
            printUsage();
            System.exit(1);
        }

        String operation  = args[0].toUpperCase();
        String ddlFilePath = args[1];

        printBanner(operation, ddlFilePath);

        // Ensure output directories exist before doing any work
        ensureDirectoryExists(DDL_OUTPUT_DIR);
        ensureDirectoryExists(PSB_OUTPUT_DIR);
        ensureDirectoryExists(DDL_RESULTS_DIR);

        switch (operation) {
            case "CREATE":
                executeCreate(ddlFilePath);
                break;
            case "ALTER":
                executeAlter(ddlFilePath);
                break;
            case "DROP":
                executeDrop(ddlFilePath);
                break;
            default:
                System.err.println("✗ Unknown operation: " + operation);
                System.err.println("  Supported operations: CREATE, ALTER, DROP");
                System.err.println("  Future operations:    VALIDATE");
                System.exit(1);
        }
    }

    // =========================================================================
    // CREATE — auto-detects DBD vs PSB and routes accordingly
    // =========================================================================

    private static void executeCreate(String ddlFilePath) {
        try {
            File ddlFile = new File(ddlFilePath);
            if (!ddlFile.exists()) {
                System.err.println("✗ DDL file not found: " + ddlFile.getAbsolutePath());
                System.exit(1);
            }

            String ddlContent = new String(Files.readAllBytes(Paths.get(ddlFilePath)));
            List<String> statements = parseDDLStatements(ddlContent);

            if (statements.isEmpty()) {
                System.err.println("✗ No DDL statements found in file: " + ddlFilePath);
                System.exit(1);
            }

            // Route based on file content
            if (isPsbDDL(statements)) {
                System.out.println("DDL type:  PSB (CREATE PROGRAMVIEW detected)");
                System.out.println();
                executePsb(ddlFilePath, statements);
            } else {
                System.out.println("DDL type:  DBD (CREATE DATABASE detected)");
                System.out.println();
                executeDBD(ddlFilePath, statements);
            }

        } catch (IOException e) {
            System.err.println("✗ File I/O error: " + e.getMessage());
            e.printStackTrace();
            System.exit(1);
        }
    }

    // =========================================================================
    // DBD DDL execution — CREATE DATABASE / TABLESPACE / TABLE + COMMIT DDL
    // =========================================================================

    private static void executeDBD(String ddlFilePath, List<String> statements) {
        String timestamp = new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date());
        String logFile   = null;
        PrintWriter log  = null;
        Connection conn  = null;
        Statement  stmt  = null;

        try {
            String dbName = extractDatabaseName(statements);
            if (dbName == null) dbName = "UNKNOWN";

            logFile = DDL_RESULTS_DIR + "/" + dbName + "_create_" + timestamp + ".log";
            log = new PrintWriter(new FileWriter(logFile));

            logHeader(log, "CREATE (DBD)", ddlFilePath, dbName, timestamp);
            System.out.println("DDL file:  " + new File(ddlFilePath).getAbsolutePath());
            System.out.println("Log file:  " + new File(logFile).getAbsolutePath());
            System.out.println();

            // ------------------------------------------------------------------
            // Validate: all DBDs (including DEDB) require DATABASE + TABLESPACE + TABLE
            // Note: DEDB uses different TABLESPACE syntax (SIZE/UOW/ROOT) but
            //       still requires a CREATE TABLESPACE statement before COMMIT DDL
            // ------------------------------------------------------------------
            boolean isDedb = isDedbDDL(statements);
            ValidationResult validation = validateDBDStatements(statements, isDedb);
            if (!validation.isValid()) {
                String msg = "✗ DBD validation failed — cannot execute:\n" + validation.getMessage();
                System.err.println(msg);
                log.println(msg);
                System.err.println("  A valid DBD DDL file must contain:");
                System.err.println("    • At least one CREATE DATABASE statement");
                System.err.println("    • At least one CREATE TABLESPACE statement");
                if (isDedb) {
                    System.err.println("      (DEDB syntax: SIZE PRIMARY <n> UOW(n,n) ROOT(n,n) — no RECORD or OVERFLOW)");
                }
                System.err.println("    • At least one CREATE TABLE statement");
                System.err.println("  COMMIT DDL will NOT be issued.");
                log.println("COMMIT DDL was NOT issued.");
                System.exit(1);
            }

            System.out.println("✓ DBD validation passed" + (isDedb ? " (DEDB)" : "") + ":");
            System.out.println("  Statements found:   " + statements.size());
            System.out.println("  CREATE DATABASE:    " + validation.dbCount);
            System.out.println("  CREATE TABLESPACE:  " + validation.tsCount);
            System.out.println("  CREATE TABLE:       " + validation.tableCount);
            System.out.println();
            log.println("Validation: PASSED" + (isDedb ? " (DEDB)" : ""));
            log.println("  CREATE DATABASE:   " + validation.dbCount);
            log.println("  CREATE TABLESPACE: " + validation.tsCount);
            log.println("  CREATE TABLE:      " + validation.tableCount);
            log.println();

            // ------------------------------------------------------------------
            // Connect
            // ------------------------------------------------------------------
            conn = openConnection(log);

            // ------------------------------------------------------------------
            // Execute statements — strip any COMMIT DDL from the list; the
            // executor issues it itself after all statements succeed
            // ------------------------------------------------------------------
            List<String> dmlStatements = new ArrayList<>();
            for (String s : statements) {
                if (!s.toUpperCase().trim().startsWith("COMMIT")) {
                    dmlStatements.add(s);
                }
            }
            int stmtNumber = executeStatements(dmlStatements, conn, log);

            // ------------------------------------------------------------------
            // All succeeded — issue COMMIT DDL
            // ------------------------------------------------------------------
            System.out.println("-".repeat(80));
            System.out.println();
            System.out.println("All statements executed successfully.");
            System.out.println("Issuing COMMIT DDL...");
            stmt = conn.createStatement();
            stmt.execute("COMMIT DDL");

            String successMsg = "✓ COMMIT DDL issued. Database '" + dbName + "' is now registered in the IMS catalog.";
            System.out.println(successMsg);
            log.println();
            log.println("COMMIT DDL: ISSUED");
            log.println(successMsg);

            // ------------------------------------------------------------------
            // Archive DDL
            // ------------------------------------------------------------------
            String outputFile = DDL_OUTPUT_DIR + "/" + dbName + "_create_" + timestamp + ".sql";
            Files.copy(Paths.get(ddlFilePath), Paths.get(outputFile));
            System.out.println();
            System.out.println("DDL archived to: " + new File(outputFile).getAbsolutePath());
            log.println("DDL archived to: " + new File(outputFile).getAbsolutePath());

            printSummary("DBD", dbName, stmtNumber, logFile, outputFile, true);
            log.println();
            log.println("Result: SUCCESS");

        } catch (IOException e) {
            System.err.println("✗ File I/O error: " + e.getMessage());
            if (log != null) log.println("File I/O error: " + e.getMessage());
            e.printStackTrace();
            System.exit(1);
        } catch (Exception e) {
            System.err.println("✗ Unexpected error: " + e.getMessage());
            if (log != null) log.println("Unexpected error: " + e.getMessage());
            e.printStackTrace();
            System.exit(1);
        } finally {
            try { if (stmt != null) stmt.close(); } catch (Exception ignored) {}
            try { if (conn != null) conn.close(); } catch (Exception ignored) {}
            if (log != null) { log.flush(); log.close(); }
        }
    }

    // =========================================================================
    // DROP — executes DROP TABLE / TABLESPACE / DATABASE statements + COMMIT DDL
    // =========================================================================

    private static void executeDrop(String ddlFilePath) {
        String timestamp = new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date());
        PrintWriter log  = null;
        Connection  conn = null;

        try {
            File ddlFile = new File(ddlFilePath);
            if (!ddlFile.exists()) {
                System.err.println("✗ DDL file not found: " + ddlFile.getAbsolutePath());
                System.exit(1);
            }

            String ddlContent = new String(Files.readAllBytes(Paths.get(ddlFilePath)));
            List<String> statements = parseDDLStatements(ddlContent);

            if (statements.isEmpty()) {
                System.err.println("✗ No DDL statements found in file: " + ddlFilePath);
                System.exit(1);
            }

            // Derive name tag from first DROP DATABASE statement
            String dbName = "UNKNOWN";
            for (String s : statements) {
                String upper = s.toUpperCase().trim();
                if (upper.startsWith("DROP DATABASE")) {
                    String[] tokens = upper.split("\\s+");
                    if (tokens.length >= 3) { dbName = tokens[2]; }
                    break;
                }
            }

            String logFile = DDL_RESULTS_DIR + "/" + dbName + "_drop_" + timestamp + ".log";
            log = new PrintWriter(new FileWriter(logFile));

            logHeader(log, "DROP", ddlFilePath, dbName, timestamp);
            System.out.println("DDL file:  " + ddlFile.getAbsolutePath());
            System.out.println("Log file:  " + new File(logFile).getAbsolutePath());
            System.out.println();

            boolean hasDropDb = statements.stream()
                    .anyMatch(s -> s.toUpperCase().trim().startsWith("DROP DATABASE"));
            if (!hasDropDb) {
                String msg = "✗ DROP validation failed — no DROP DATABASE statement found.";
                System.err.println(msg);
                log.println(msg);
                System.exit(1);
            }

            long dropCount = statements.stream()
                    .filter(s -> s.toUpperCase().trim().startsWith("DROP")).count();
            System.out.println("✓ DROP validation passed:");
            System.out.println("  Statements found:   " + statements.size());
            System.out.println("  DROP statements:    " + dropCount);
            System.out.println();
            log.println("Validation: PASSED");
            log.println("  DROP statements: " + dropCount);
            log.println();

            conn = openConnection(log);
            int stmtNumber = executeStatements(statements, conn, log);

            System.out.println("-".repeat(80));
            System.out.println();
            String successMsg = "✓ DROP completed. Database '" + dbName
                              + "' has been removed from the IMS catalog.";
            System.out.println(successMsg);
            log.println();
            log.println(successMsg);

            printSummary("DROP", dbName, stmtNumber, logFile, ddlFilePath, true);
            log.println();
            log.println("Result: SUCCESS");

        } catch (IOException e) {
            System.err.println("✗ File I/O error: " + e.getMessage());
            if (log != null) log.println("File I/O error: " + e.getMessage());
            e.printStackTrace();
            System.exit(1);
        } catch (Exception e) {
            System.err.println("✗ Unexpected error: " + e.getMessage());
            if (log != null) log.println("Unexpected error: " + e.getMessage());
            e.printStackTrace();
            System.exit(1);
        } finally {
            try { if (conn != null) conn.close(); } catch (Exception ignored) {}
            if (log != null) { log.flush(); log.close(); }
        }
    }

    // =========================================================================
    // ALTER — executes ALTER TABLE statements and issues COMMIT DDL
    // =========================================================================

    private static void executeAlter(String ddlFilePath) {
        String timestamp = new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date());
        PrintWriter log  = null;
        Connection  conn = null;

        try {
            File ddlFile = new File(ddlFilePath);
            if (!ddlFile.exists()) {
                System.err.println("✗ DDL file not found: " + ddlFile.getAbsolutePath());
                System.exit(1);
            }

            String ddlContent  = new String(Files.readAllBytes(Paths.get(ddlFilePath)));
            List<String> statements = parseDDLStatements(ddlContent);

            if (statements.isEmpty()) {
                System.err.println("✗ No DDL statements found in file: " + ddlFilePath);
                System.exit(1);
            }

            // Derive a name tag from the first ALTER TABLE statement
            String tableTag = "UNKNOWN";
            for (String s : statements) {
                String upper = s.toUpperCase().trim();
                if (upper.startsWith("ALTER TABLE")) {
                    String[] tokens = upper.split("\\s+");
                    if (tokens.length >= 3) { tableTag = tokens[2].replaceAll("[^A-Z0-9._]", ""); }
                    break;
                }
            }

            String logFile = DDL_RESULTS_DIR + "/" + tableTag.replace('.', '_')
                           + "_alter_" + timestamp + ".log";
            log = new PrintWriter(new FileWriter(logFile));

            logHeader(log, "ALTER", ddlFilePath, tableTag, timestamp);
            System.out.println("DDL file:  " + ddlFile.getAbsolutePath());
            System.out.println("Log file:  " + new File(logFile).getAbsolutePath());
            System.out.println();

            // Validate: must contain at least one ALTER TABLE statement
            boolean hasAlter = statements.stream()
                    .anyMatch(s -> s.toUpperCase().trim().startsWith("ALTER TABLE"));
            if (!hasAlter) {
                String msg = "✗ ALTER validation failed — no ALTER TABLE statement found.";
                System.err.println(msg);
                log.println(msg);
                System.exit(1);
            }

            long alterCount = statements.stream()
                    .filter(s -> s.toUpperCase().trim().startsWith("ALTER TABLE")).count();
            System.out.println("✓ ALTER validation passed:");
            System.out.println("  Statements found:   " + statements.size());
            System.out.println("  ALTER TABLE:        " + alterCount);
            System.out.println();
            log.println("Validation: PASSED");
            log.println("  ALTER TABLE: " + alterCount);
            log.println();

            // Connect and execute — COMMIT DDL is included in each statement block in the DDL file
            conn = openConnection(log);
            int stmtNumber = executeStatements(statements, conn, log);

            System.out.println("-".repeat(80));
            System.out.println();
            String successMsg = "✓ All statements executed successfully. Alterations to '" + tableTag
                              + "' are registered in the IMS catalog.";
            System.out.println(successMsg);
            log.println();
            log.println(successMsg);

            printSummary("ALTER", tableTag, stmtNumber, logFile, ddlFilePath, true);
            log.println();
            log.println("Result: SUCCESS");

        } catch (IOException e) {
            System.err.println("✗ File I/O error: " + e.getMessage());
            if (log != null) log.println("File I/O error: " + e.getMessage());
            e.printStackTrace();
            System.exit(1);
        } catch (Exception e) {
            System.err.println("✗ Unexpected error: " + e.getMessage());
            if (log != null) log.println("Unexpected error: " + e.getMessage());
            e.printStackTrace();
            System.exit(1);
        } finally {
            try { if (conn != null) conn.close(); } catch (Exception ignored) {}
            if (log != null) { log.flush(); log.close(); }
        }
    }

    // =========================================================================
    // PSB DDL execution — CREATE PROGRAMVIEW + COMMIT DDL (inline in file)
    // =========================================================================

    private static void executePsb(String ddlFilePath, List<String> statements) {
        String timestamp = new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date());
        String logFile   = null;
        PrintWriter log  = null;
        Connection conn  = null;

        try {
            String psbName = extractProgramViewName(statements);
            if (psbName == null) psbName = "UNKNOWN";

            logFile = DDL_RESULTS_DIR + "/" + psbName + "_psb_" + timestamp + ".log";
            log = new PrintWriter(new FileWriter(logFile));

            logHeader(log, "CREATE (PSB)", ddlFilePath, psbName, timestamp);
            System.out.println("PSB file:  " + new File(ddlFilePath).getAbsolutePath());
            System.out.println("Log file:  " + new File(logFile).getAbsolutePath());
            System.out.println();

            // ------------------------------------------------------------------
            // Validate: must have CREATE PROGRAMVIEW and COMMIT
            // ------------------------------------------------------------------
            boolean hasProgramView = statements.stream()
                    .anyMatch(s -> s.toUpperCase().trim().startsWith("CREATE PROGRAMVIEW"));
            boolean hasCommit = statements.stream()
                    .anyMatch(s -> s.toUpperCase().trim().equals("COMMIT DDL"));

            if (!hasProgramView || !hasCommit) {
                List<String> missing = new ArrayList<>();
                if (!hasProgramView) missing.add("CREATE PROGRAMVIEW");
                if (!hasCommit)      missing.add("COMMIT DDL");
                String msg = "✗ PSB validation failed — missing: " + String.join(", ", missing);
                System.err.println(msg);
                log.println(msg);
                System.exit(1);
            }

            System.out.println("✓ PSB validation passed:");
            System.out.println("  Statements found:      " + statements.size());
            System.out.println("  CREATE PROGRAMVIEW:    1");
            System.out.println("  COMMIT DDL:            1");
            System.out.println();
            log.println("Validation: PASSED");
            log.println("  CREATE PROGRAMVIEW: 1");
            log.println("  COMMIT DDL:         1");
            log.println();

            // ------------------------------------------------------------------
            // Connect
            // ------------------------------------------------------------------
            conn = openConnection(log);

            // ------------------------------------------------------------------
            // Execute all statements (COMMIT is the last statement in the file)
            // ------------------------------------------------------------------
            executeStatements(statements, conn, log);

            String successMsg = "✓ PSB '" + psbName + "' is now registered in the IMS catalog.";
            System.out.println("-".repeat(80));
            System.out.println();
            System.out.println(successMsg);
            log.println();
            log.println(successMsg);

            // ------------------------------------------------------------------
            // Archive PSB DDL
            // ------------------------------------------------------------------
            String outputFile = PSB_OUTPUT_DIR + "/" + psbName + "_psb_" + timestamp + ".sql";
            // Only copy if source is not already in psb-output
            if (!new File(ddlFilePath).getAbsolutePath()
                    .equals(new File(outputFile).getAbsolutePath())) {
                Files.copy(Paths.get(ddlFilePath), Paths.get(outputFile));
            }
            System.out.println("PSB DDL archived to: " + new File(outputFile).getAbsolutePath());
            log.println("PSB DDL archived to: " + new File(outputFile).getAbsolutePath());

            printSummary("PSB", psbName, statements.size(), logFile, outputFile, true);
            log.println();
            log.println("Result: SUCCESS");

        } catch (IOException e) {
            System.err.println("✗ File I/O error: " + e.getMessage());
            if (log != null) log.println("File I/O error: " + e.getMessage());
            e.printStackTrace();
            System.exit(1);
        } catch (Exception e) {
            System.err.println("✗ Unexpected error: " + e.getMessage());
            if (log != null) log.println("Unexpected error: " + e.getMessage());
            e.printStackTrace();
            System.exit(1);
        } finally {
            try { if (conn != null) conn.close(); } catch (Exception ignored) {}
            if (log != null) { log.flush(); log.close(); }
        }
    }

    // =========================================================================
    // Shared execution helpers
    // =========================================================================

    /** Opens a JDBC connection using the DDL catalog PSB. */
    private static Connection openConnection(PrintWriter log) throws Exception {
        System.out.println("Connecting to IMS (DDL catalog PSB: " + DDL_PSB + ")...");
        if (log != null) log.println("Connecting to " + HOST + ":" + PORT + " PSB=" + DDL_PSB);
        Class.forName("com.ibm.ims.jdbc.IMSDriver");
        String url = "jdbc:ims://" + HOST + ":" + PORT + "/" + DDL_PSB
                   + ":user=" + USER + ";password=" + PASSWORD + ";";
        Connection conn = DriverManager.getConnection(url);
        System.out.println("✓ Connected successfully.");
        System.out.println();
        if (log != null) log.println("Connected successfully.");
        return conn;
    }

    /**
     * Executes a list of statements in order against the given connection.
     * Stops and exits on the first failure. Returns the count of statements executed.
     */
    private static int executeStatements(List<String> statements,
                                         Connection conn, PrintWriter log) throws Exception {
        System.out.println("Executing statements...");
        System.out.println("-".repeat(80));

        int stmtNumber = 0;
        int total = statements.size();
        for (String sql : statements) {
            stmtNumber++;
            String trimmed = sql.trim();
            if (trimmed.isEmpty()) continue;

            System.out.printf("  [%d/%d] %s%n", stmtNumber, total, summarise(trimmed));
            log.printf("[%d/%d] %s%n", stmtNumber, total, trimmed);

            try {
                Statement stmt = conn.createStatement();
                stmt.execute(trimmed);
                stmt.close();
                System.out.println("         ✓ OK");
                log.println("         → OK");
            } catch (Exception e) {
                System.err.println();
                System.err.println("✗ Statement " + stmtNumber + " FAILED: " + e.getMessage());
                log.println("         → FAILED: " + e.getMessage());
                log.println();
                log.println("Execution halted at statement " + stmtNumber + ". COMMIT DDL was NOT issued.");
                System.err.println("COMMIT was NOT issued.");
                e.printStackTrace();
                System.exit(1);
            }
        }
        return stmtNumber;
    }

    // =========================================================================
    // DDL parsing
    // =========================================================================

    /**
     * Splits DDL file content into individual statements on ";" boundaries.
     * Strips single-line comments (--) and blank lines.
     */
    private static List<String> parseDDLStatements(String content) {
        List<String> statements = new ArrayList<>();
        String stripped = content.replaceAll("(?m)^\\s*--.*$", "");
        String[] parts = stripped.split(";");
        for (String part : parts) {
            String trimmed = part.trim();
            if (!trimmed.isEmpty()) {
                statements.add(trimmed);
            }
        }
        return statements;
    }

    /** Returns true if the statements represent PSB DDL (CREATE PROGRAMVIEW). */
    private static boolean isPsbDDL(List<String> statements) {
        return statements.stream()
                .anyMatch(s -> s.toUpperCase().trim().startsWith("CREATE PROGRAMVIEW"));
    }

    /** Returns true if the DDL creates a DEDB (ACCESS DEDB on the CREATE DATABASE statement). */
    private static boolean isDedbDDL(List<String> statements) {
        return statements.stream()
                .anyMatch(s -> s.toUpperCase().replaceAll("\\s+", " ").contains("ACCESS DEDB"));
    }

    /** Extracts the database name from the first CREATE DATABASE statement. */
    private static String extractDatabaseName(List<String> statements) {
        for (String s : statements) {
            String upper = s.toUpperCase().trim();
            if (upper.startsWith("CREATE DATABASE")) {
                String[] tokens = upper.split("\\s+");
                if (tokens.length >= 3) return tokens[2];
            }
        }
        return null;
    }

    /** Extracts the PSB name from the first CREATE PROGRAMVIEW statement. */
    private static String extractProgramViewName(List<String> statements) {
        for (String s : statements) {
            String upper = s.toUpperCase().trim();
            if (upper.startsWith("CREATE PROGRAMVIEW")) {
                String[] tokens = upper.split("\\s+");
                if (tokens.length >= 3) return tokens[2].replaceAll("[^A-Z0-9]", "");
            }
        }
        return null;
    }

    // =========================================================================
    // Validation
    // =========================================================================

    private static ValidationResult validateDBDStatements(List<String> statements, boolean isDedb) {
        int dbCount    = 0;
        int tsCount    = 0;
        int tableCount = 0;
        for (String s : statements) {
            String upper = s.toUpperCase().trim();
            if      (upper.startsWith("CREATE DATABASE"))   dbCount++;
            else if (upper.startsWith("CREATE TABLESPACE")) tsCount++;
            else if (upper.startsWith("CREATE TABLE"))      tableCount++;
        }
        List<String> missing = new ArrayList<>();
        if (dbCount    == 0) missing.add("CREATE DATABASE");
        if (tsCount    == 0) missing.add("CREATE TABLESPACE");
        if (tableCount == 0) missing.add("CREATE TABLE");

        return new ValidationResult(missing.isEmpty(), dbCount, tsCount, tableCount,
                missing.isEmpty() ? "" : "  Missing: " + String.join(", ", missing));
    }

    // =========================================================================
    // Helpers
    // =========================================================================

    private static void printBanner(String operation, String ddlFile) {
        System.out.println("=".repeat(80));
        System.out.println("IMS DBA Executor — Generated by Bob for Z");
        System.out.println("=".repeat(80));
        System.out.println("Operation: " + operation);
        System.out.println("DDL file:  " + ddlFile);
        System.out.println("Timestamp: " + new Date());
        System.out.println("=".repeat(80));
        System.out.println();
    }


    private static void printUsage() {
        System.err.println("Usage:   IMSDBAExecutor <OPERATION> <ddl_file>");
        System.err.println("Example: IMSDBAExecutor CREATE ../ddl-output/MYDB_create.sql");
        System.err.println("         IMSDBAExecutor CREATE ../psb-output/MYPSB_psb.sql");
        System.err.println("         IMSDBAExecutor ALTER  ../ddl-output/MYDB_editor_<ts>.sql");
        System.err.println("         IMSDBAExecutor DROP   ../ddl-output/MYDB_drop.sql");
        System.err.println();
        System.err.println("Supported operations: CREATE, ALTER, DROP");
        System.err.println("Future operations:    VALIDATE");
        System.err.println();
        System.err.println("Note: DDL files must use COMMIT DDL (not plain COMMIT).");
    }

    private static void printSummary(String type, String name, int stmtCount,
                                     String logFile, String outputFile, boolean success) {
        System.out.println();
        System.out.println("=".repeat(80));
        System.out.println(success
                ? "✓ " + type + " CREATE completed successfully!"
                : "✗ " + type + " CREATE failed.");
        System.out.println("  Name:               " + name);
        System.out.println("  Statements executed:" + stmtCount);
        System.out.println("  DDL archived to:    " + new File(outputFile).getAbsolutePath());
        System.out.println("  Execution log:      " + new File(logFile).getAbsolutePath());
        System.out.println("=".repeat(80));
    }

    private static void logHeader(PrintWriter log, String operation,
                                  String ddlFile, String name, String timestamp) {
        log.println("=".repeat(80));
        log.println("IMS DBA Executor — Execution Log");
        log.println("=".repeat(80));
        log.println("Operation:  " + operation);
        log.println("Name:       " + name);
        log.println("DDL file:   " + ddlFile);
        log.println("Timestamp:  " + timestamp);
        log.println("User:       " + USER);
        log.println("Host:       " + HOST + ":" + PORT);
        log.println("=".repeat(80));
        log.println();
    }

    private static void ensureDirectoryExists(String path) {
        File dir = new File(path);
        if (!dir.exists()) dir.mkdirs();
    }

    /** Returns a one-line summary of a DDL statement for console display. */
    private static String summarise(String sql) {
        String oneLine = sql.replaceAll("\\s+", " ").trim();
        return oneLine.length() > 72 ? oneLine.substring(0, 72) + "..." : oneLine;
    }

    // =========================================================================
    // Inner types
    // =========================================================================

    private static class ValidationResult {
        final boolean isValid;
        final int     dbCount;
        final int     tsCount;
        final int     tableCount;
        final String  message;

        ValidationResult(boolean isValid, int dbCount, int tsCount,
                         int tableCount, String message) {
            this.isValid    = isValid;
            this.dbCount    = dbCount;
            this.tsCount    = tsCount;
            this.tableCount = tableCount;
            this.message    = message;
        }

        boolean isValid()    { return isValid; }
        String  getMessage() { return message; }
    }
}
