package com.ibm.ims.jdbcbob;

import java.io.File;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

/**
 * IMS DDL File Executor — Generated by Bob for Z
 *
 * Executes IMS DDL contained in a plain-text file.
 * Statements are separated by semicolons (;). Single-line comments (-- ...)
 * are stripped before parsing. A COMMIT DDL statement must be present in
 * the file to persist changes to the IMS catalog.
 *
 * Usage:
 *   mvn exec:java -Dexec.mainClass="com.ibm.ims.jdbcbob.IMSDDLFileExecutor" \
 *     -Dexec.args="<path_to_ddl_file>"
 *
 * Example:
 *   mvn exec:java -Dexec.mainClass="com.ibm.ims.jdbcbob.IMSDDLFileExecutor" \
 *     -Dexec.args="../ddl-output/MyDB_create.sql"
 */
public class IMSDDLFileExecutor {

    private static final String HOST     = IMSConnectionConfig.HOST;
    private static final int    PORT     = IMSConnectionConfig.PORT;
    private static final String USER     = IMSConnectionConfig.USER;
    private static final String PASSWORD = IMSConnectionConfig.PASSWORD;
    private static final String DDL_PSB  = IMSConnectionConfig.DDL_PSB;

    public static void main(String[] args) throws Exception {
        if (args.length < 1) {
            System.err.println("Usage: IMSDDLFileExecutor <path_to_ddl_file>");
            System.err.println("Example: IMSDDLFileExecutor ../ddl-output/MyDB_create.sql");
            System.exit(1);
        }

        String ddlFilePath = args[0];
        File   ddlFile     = new File(ddlFilePath);

        if (!ddlFile.exists()) {
            System.err.println("✗ DDL file not found: " + ddlFile.getAbsolutePath());
            System.exit(1);
        }

        System.out.println("=".repeat(80));
        System.out.println("IMS DDL File Executor — Generated by Bob for Z");
        System.out.println("=".repeat(80));
        System.out.println("DDL file: " + ddlFile.getAbsolutePath());
        System.out.println("=".repeat(80));
        System.out.println();

        // Read and parse the DDL file
        String content = new String(Files.readAllBytes(Paths.get(ddlFilePath)));
        List<String> statements = parseDDLStatements(content);

        if (statements.isEmpty()) {
            System.err.println("✗ No DDL statements found in file: " + ddlFilePath);
            System.exit(1);
        }

        System.out.println("Statements to execute: " + statements.size());
        System.out.println();

        // Connect using the DDL catalog PSB
        System.out.println("Connecting to IMS (DDL catalog PSB: " + DDL_PSB + ")...");
        Class.forName("com.ibm.ims.jdbc.IMSDriver");
        String url = "jdbc:ims://" + HOST + ":" + PORT + "/" + DDL_PSB
                   + ":user=" + USER + ";password=" + PASSWORD + ";";

        try (Connection conn = DriverManager.getConnection(url)) {
            System.out.println("✓ Connected successfully.");
            System.out.println();

            int total = statements.size();
            for (int i = 0; i < total; i++) {
                String sql = statements.get(i).trim();
                System.out.printf("  [%d/%d] %s%n", i + 1, total, summarise(sql));
                try (Statement stmt = conn.createStatement()) {
                    stmt.execute(sql);
                }
                System.out.println("         ✓ OK");
            }

            System.out.println();
            System.out.println("✓ All statements executed successfully.");
        }
    }

    /** Splits DDL content into individual statements on ";" boundaries. Strips "--" comments. */
    private static List<String> parseDDLStatements(String content) {
        List<String> result = new ArrayList<>();
        String stripped = content.replaceAll("(?m)^\\s*--.*$", "");
        for (String part : stripped.split(";")) {
            String trimmed = part.trim();
            if (!trimmed.isEmpty()) {
                result.add(trimmed);
            }
        }
        return result;
    }

    /** Returns a one-line summary of a DDL statement for console display. */
    private static String summarise(String sql) {
        String oneLine = sql.replaceAll("\\s+", " ").trim();
        return oneLine.length() > 72 ? oneLine.substring(0, 72) + "..." : oneLine;
    }
}
