package com.ibm.ims.jdbcbob;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.util.Date;

/**
 * Universal IMS Insert Executor — Generated by Bob for Z
 *
 * Executes one or more INSERT statements against an IMS database over JDBC Type-4.
 * The PSB name (database argument) is used as the target PSB in the JDBC URL.
 * Each INSERT statement is passed as a separate argument after the PSB name.
 *
 * Usage:
 *   mvn exec:java -Dexec.mainClass="com.ibm.ims.jdbcbob.IMSInsertExecutor" \
 *     -Dexec.args="<PSB_NAME> \"<INSERT_SQL_1>\" \"<INSERT_SQL_2>\" ..."
 *
 * Example:
 *   mvn exec:java -Dexec.mainClass="com.ibm.ims.jdbcbob.IMSInsertExecutor" \
 *     -Dexec.args="DFSSAMT4 \"INSERT INTO DBPCB01.PARTROOT (PARTKEY) VALUES ('BOLT-001')\""
 */
public class IMSInsertExecutor {

    private static final String HOST     = IMSConnectionConfig.HOST;
    private static final int    PORT     = IMSConnectionConfig.PORT;
    private static final String USER     = IMSConnectionConfig.USER;
    private static final String PASSWORD = IMSConnectionConfig.PASSWORD;

    public static void main(String[] args) {

        if (args.length < 2) {
            System.err.println("Usage: IMSInsertExecutor <psb_name> <insert_sql> [<insert_sql_2> ...]");
            System.err.println("Example: IMSInsertExecutor DFSSAMT4 \"INSERT INTO DBPCB01.PARTROOT (PARTKEY) VALUES ('BOLT-001')\"");
            System.exit(1);
        }

        String databaseName = args[0];

        Connection connection = null;
        Statement  statement  = null;

        try {
            System.out.println("=".repeat(80));
            System.out.println("IMS Insert Executor — Generated by Bob for Z");
            System.out.println("=".repeat(80));
            System.out.println("PSB/Database: " + databaseName);
            System.out.println("Statements  : " + (args.length - 1));
            System.out.println("Timestamp   : " + new Date());
            System.out.println("=".repeat(80));
            System.out.println();

            // Establish JDBC Type-4 connection using DriverManager URL pattern
            System.out.println("Connecting to IMS PSB " + databaseName + "...");
            Class.forName("com.ibm.ims.jdbc.IMSDriver");
            String url = "jdbc:ims://" + HOST + ":" + PORT + "/" + databaseName
                       + ":user=" + USER + ";password=" + PASSWORD + ";";
            connection = DriverManager.getConnection(url);
            System.out.println("✓ Connected successfully!");
            System.out.println();

            statement = connection.createStatement();

            int totalInserted = 0;

            // Execute each INSERT statement supplied as an argument
            for (int i = 1; i < args.length; i++) {
                String sql = args[i];
                System.out.println("--- INSERT " + i + " ---");
                System.out.println("SQL: " + sql);

                int rows = statement.executeUpdate(sql);
                totalInserted += rows;

                System.out.println("✓ Rows affected: " + rows);
                System.out.println();
            }

            // Commit all inserts
            connection.commit();

            System.out.println("=".repeat(80));
            System.out.println("✓ All inserts committed successfully!");
            System.out.println("Total rows inserted: " + totalInserted);
            System.out.println("=".repeat(80));

        } catch (Exception e) {
            System.err.println();
            System.err.println("=".repeat(80));
            System.err.println("✗ Error during INSERT execution:");
            System.err.println("=".repeat(80));
            System.err.println("Message: " + e.getMessage());
            System.err.println();
            System.err.println("Troubleshooting tips:");
            System.err.println("1. Verify the PCB name is correct (use IMSMetadataExplorer to discover it)");
            System.err.println("2. Check that the table/segment name is correct");
            System.err.println("3. Ensure all required columns are supplied in the INSERT");
            System.err.println("4. Verify you have INSERT access to the PCB");
            System.err.println("=".repeat(80));
            e.printStackTrace();

            // Attempt rollback on failure
            try {
                if (connection != null) {
                    connection.rollback();
                    System.err.println("Transaction rolled back.");
                }
            } catch (Exception rb) {
                System.err.println("Rollback failed: " + rb.getMessage());
            }

            System.exit(1);

        } finally {
            try {
                if (statement  != null) statement.close();
                if (connection != null) connection.close();
                System.out.println("Database connection closed.");
            } catch (Exception e) {
                System.err.println("Error closing resources: " + e.getMessage());
            }
        }
    }
}
