package com.ibm.ims.jdbcbob;

import com.ibm.ims.jdbc.IMSDataSource;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;

/**
 * IMS Metadata Explorer
 * Generated by Bob for Z - Discovers PCB names, tables, and columns in IMS databases
 * 
 * Usage: java IMSMetadataExplorer "<database>"
 * Example: java IMSMetadataExplorer "DFSIVP37"
 */
public class IMSMetadataExplorer {
    private static final String HOST     = IMSConnectionConfig.HOST;
    private static final int    PORT     = IMSConnectionConfig.PORT;
    private static final String USER     = IMSConnectionConfig.USER;
    private static final String PASSWORD = IMSConnectionConfig.PASSWORD;
    
    public static void main(String[] args) {
        if (args.length < 1) {
            System.err.println("Usage: java IMSMetadataExplorer <database>");
            System.err.println("Example: java IMSMetadataExplorer \"DFSIVP37\"");
            System.exit(1);
        }
        
        String databaseName = args[0];
        Connection connection = null;
        
        try {
            System.out.println("=".repeat(80));
            System.out.println("IMS Metadata Explorer - Generated by Bob for Z");
            System.out.println("=".repeat(80));
            System.out.println("Database: " + databaseName);
            System.out.println("=".repeat(80));
            System.out.println();
            
            // Create IMS connection
            IMSDataSource ds = new IMSDataSource();
            ds.setHost(HOST);
            ds.setPortNumber(PORT);
            ds.setDriverType(4);
            ds.setUser(USER);
            ds.setPassword(PASSWORD);
            ds.setDatabaseName(databaseName);
            connection = ds.getConnection();
            
            System.out.println("✓ Connected successfully to " + databaseName);
            System.out.println();
            
            DatabaseMetaData dbmd = connection.getMetaData();
            
            // Step 1: List all PCBs (schemas) in the database
            System.out.println("=".repeat(80));
            System.out.println("STEP 1: Discovering PCB Names (Schemas)");
            System.out.println("=".repeat(80));
            
            ResultSet schemas = null;
            try {
                schemas = dbmd.getSchemas(databaseName, null);
                ResultSetMetaData rsmd = schemas.getMetaData();
                int colCount = rsmd.getColumnCount();
                
                System.out.println("\nAvailable PCBs in " + databaseName + ":");
                System.out.println("-".repeat(80));
                
                int pcbCount = 0;
                while (schemas.next()) {
                    pcbCount++;
                    System.out.println("\nPCB #" + pcbCount + ":");
                    for (int i = 1; i <= colCount; i++) {
                        String columnName = rsmd.getColumnName(i);
                        String value = schemas.getString(i);
                        System.out.println("  " + columnName + ": " + (value != null ? value : "NULL"));
                    }
                }
                
                if (pcbCount == 0) {
                    System.out.println("  No PCBs found via getSchemas()");
                    System.out.println("  This may indicate a catalog configuration issue.");
                    System.out.println("  Attempting alternative discovery method...");
                }
                
                System.out.println("\n" + "=".repeat(80));
                System.out.println("Total PCBs found via getSchemas(): " + pcbCount);
                System.out.println("=".repeat(80));
                System.out.println();
                
                // Step 2: For each PCB, list tables/segments
                if (pcbCount > 0) {
                    schemas = dbmd.getSchemas(databaseName, null);
                    while (schemas.next()) {
                        String pcbName = schemas.getString("TABLE_SCHEM");
                        if (pcbName != null) {
                            System.out.println("=".repeat(80));
                            System.out.println("STEP 2: Tables/Segments in PCB: " + pcbName);
                            System.out.println("=".repeat(80));
                            
                            ResultSet tables = dbmd.getTables(databaseName, pcbName, null, null);
                            ResultSetMetaData tablesRsmd = tables.getMetaData();
                            int tablesColCount = tablesRsmd.getColumnCount();
                            
                            int tableCount = 0;
                            while (tables.next()) {
                                tableCount++;
                                System.out.println("\nTable/Segment #" + tableCount + ":");
                                for (int i = 1; i <= tablesColCount; i++) {
                                    String columnName = tablesRsmd.getColumnName(i);
                                    String value = tables.getString(i);
                                    System.out.println("  " + columnName + ": " + (value != null ? value : "NULL"));
                                }
                            }
                            tables.close();
                            
                            if (tableCount == 0) {
                                System.out.println("  No tables/segments found in this PCB");
                            }
                            
                            System.out.println("\nTotal tables/segments in " + pcbName + ": " + tableCount);
                            System.out.println();
                        }
                    }
                }
                
            } catch (Exception catalogError) {
                System.err.println("\n⚠ WARNING: IMS Catalog access failed!");
                System.err.println("Error: " + catalogError.getMessage());
                System.err.println("\nThis database has catalog configuration issues.");
                System.err.println("The IMS administrator needs to fix the catalog XML for DBD.");
                System.err.println("\nYou must manually provide the PCB name to query this database.");
                System.err.println("Contact your IMS administrator for the correct PCB names.");
            } finally {
                if (schemas != null) schemas.close();
            }
            
            // Step 3: Show example query format
            System.out.println("=".repeat(80));
            System.out.println("STEP 3: How to Use This Information");
            System.out.println("=".repeat(80));
            System.out.println("\nTo query IMS data, use this format:");
            System.out.println("  SELECT * FROM \"PCB_NAME\".\"TABLE_NAME\"");
            System.out.println("\nExample based on discovered metadata:");
            System.out.println("  SELECT * FROM \"<PCB_NAME>\".\"<TABLE_NAME>\"");
            System.out.println("\nReplace <PCB_NAME> and <TABLE_NAME> with actual values from above.");
            System.out.println("\nIf metadata discovery failed, you MUST ask your IMS administrator");
            System.out.println("for the correct PCB names. DO NOT GUESS!");
            System.out.println("=".repeat(80));
            
            connection.commit();
            connection.close();
            
            System.out.println("\n✓ Metadata exploration completed!");
            
        } catch (Exception e) {
            System.err.println("\n" + "=".repeat(80));
            System.err.println("✗ Error occurred while exploring metadata:");
            System.err.println("=".repeat(80));
            System.err.println("Error message: " + e.getMessage());
            System.err.println();
            System.err.println("This could mean:");
            System.err.println("1. The database name is incorrect");
            System.err.println("2. You don't have permissions to access metadata");
            System.err.println("3. The IMS catalog is not properly configured");
            System.err.println("=".repeat(80));
            e.printStackTrace();
            System.exit(1);
            
        } finally {
            try {
                if (connection != null) connection.close();
            } catch (Exception e) {
                System.err.println("Error closing connection: " + e.getMessage());
            }
        }
    }
}