package com.ibm.ims.jdbcbob;

import com.ibm.ims.jdbc.IMSDataSource;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Query all records from PARTROOT table in DFSSAM09 database
 * Generated by Bob for Z based on user request: "Connect to database DFSSAM09, i want to see everything in the partroot table"
 * Results are exported to CSV file for retention
 */
public class QueryPartRoot {
    // Directory to store query results - can be customized
    private static final String RESULTS_DIR = "query_results";
    
    public static void main(String[] args) {
        Connection connection = null;
        Statement statement = null;
        ResultSet resultSet = null;
        PrintWriter csvWriter = null;
        
        try {
            // Create results directory if it doesn't exist
            File resultsDir = new File(RESULTS_DIR);
            if (!resultsDir.exists()) {
                resultsDir.mkdirs();
                System.out.println("Created results directory: " + resultsDir.getAbsolutePath());
            }
            
            // Generate timestamped filename for CSV export
            String timestamp = new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date());
            String csvFilename = RESULTS_DIR + "/PARTROOT_query_" + timestamp + ".csv";
            csvWriter = new PrintWriter(new FileWriter(csvFilename));
            
            System.out.println("Connecting to IMS database DFSSAM09...");
            
            // Create IMS connection
            IMSDataSource ds = new IMSDataSource();
            ds.setHost(IMSConnectionConfig.HOST);
            ds.setPortNumber(IMSConnectionConfig.PORT);
            ds.setDriverType(4);
            ds.setUser(IMSConnectionConfig.USER);
            ds.setPassword(IMSConnectionConfig.PASSWORD);
            ds.setDatabaseName("DFSSAM09");
            connection = ds.getConnection();
            
            System.out.println("Connected successfully!");
            System.out.println("Executing query: SELECT * FROM PCB01.PARTROOT");
            System.out.println("Results will be saved to: " + csvFilename);
            System.out.println();
            
            // Execute query to get all records from PARTROOT
            String sql = "SELECT * FROM PCB01.PARTROOT";
            statement = connection.createStatement();
            resultSet = statement.executeQuery(sql);
            
            // Get metadata to display column names
            ResultSetMetaData rsmd = resultSet.getMetaData();
            int columnCount = rsmd.getColumnCount();
            
            // Write CSV header
            for (int i = 1; i <= columnCount; i++) {
                csvWriter.print(rsmd.getColumnName(i));
                if (i < columnCount) {
                    csvWriter.print(",");
                }
            }
            csvWriter.println();
            
            // Display column headers to console
            System.out.println("=== PARTROOT Table Contents ===");
            for (int i = 1; i <= columnCount; i++) {
                System.out.print(rsmd.getColumnName(i));
                if (i < columnCount) {
                    System.out.print(" | ");
                }
            }
            System.out.println();
            System.out.println("=".repeat(80));
            
            // Display and export all records
            int recordCount = 0;
            while (resultSet.next()) {
                recordCount++;
                System.out.println("\nRecord #" + recordCount + ":");
                
                // Write to CSV and display to console
                for (int i = 1; i <= columnCount; i++) {
                    String columnName = rsmd.getColumnName(i);
                    String value = resultSet.getString(i);
                    String displayValue = (value != null ? value : "NULL");
                    
                    // Display to console
                    System.out.println("  " + columnName + ": " + displayValue);
                    
                    // Write to CSV (escape commas and quotes)
                    if (value != null) {
                        // Escape quotes and wrap in quotes if contains comma
                        if (value.contains(",") || value.contains("\"") || value.contains("\n")) {
                            value = "\"" + value.replace("\"", "\"\"") + "\"";
                        }
                        csvWriter.print(value);
                    }
                    
                    if (i < columnCount) {
                        csvWriter.print(",");
                    }
                }
                csvWriter.println();
            }
            
            System.out.println("\n" + "=".repeat(80));
            System.out.println("Total records retrieved: " + recordCount);
            System.out.println("Results saved to: " + new File(csvFilename).getAbsolutePath());
            
            // Commit and close connection
            connection.commit();
            System.out.println("\nQuery completed successfully!");
            
        } catch (Exception e) {
            System.err.println("Error occurred while querying PARTROOT table:");
            System.err.println("Error message: " + e.getMessage());
            e.printStackTrace();
            
        } finally {
            // Clean up resources
            try {
                if (csvWriter != null) {
                    csvWriter.close();
                    System.out.println("CSV file closed and saved.");
                }
                if (resultSet != null) resultSet.close();
                if (statement != null) statement.close();
                if (connection != null) connection.close();
                System.out.println("Database connection closed.");
            } catch (Exception e) {
                System.err.println("Error closing resources: " + e.getMessage());
            }
        }
    }
}