CREATE PROGRAMVIEW DBFSAMP1 (
    CREATE SCHEMA CUSPCB USING DBFSAMP1
        AS CUSPCB (
            CREATE SENSEGVIEW CHCKSEGM,
            CREATE SENSEGVIEW CHCKTRSG,
            CREATE SENSEGVIEW CURRSEGM,
            CREATE SENSEGVIEW CURRTRSG,
            CREATE SENSEGVIEW CUSDEPSG,
            CREATE SENSEGVIEW CUSTADDR,
            CREATE SENSEGVIEW CUSTROOT,
            CREATE SENSEGVIEW SAVESEGM,
            CREATE SENSEGVIEW SAVETRSG
        )
        PROCOPT 'AP' LISTYES
        POSSNGL SBCOND
) CMPATYES GSROLBOKNO OLICYES LOCKMAX 0 IOASIZE 600 SSASIZE 840
    LANGASSEM;

COMMIT DDL;
