CREATE PROGRAMVIEW DBFSAMP5 (
    CREATE SCHEMA LOANPCB USING DBFSAMP5
        AS LOANPCB (
            CREATE SENSEGVIEW CUSTROOT,
            CREATE SENSEGVIEW LOANSEGM
        )
        PROCOPT 'AP' LISTYES
        POSSNGL SBCOND
) CMPATYES GSROLBOKNO OLICYES LOCKMAX 0 IOASIZE 600 SSASIZE 840
    LANGASSEM;

COMMIT DDL;
