-- EDITOR (NLP): Add PARTINFO to PARTROOT in DFSSAM09 (DBD: DI21PART)
-- Generated: 2026-09-21 08:43:58

ALTER TABLE PARTROOT IN DATABASE DI21PART
    ADD COLUMN PARTINFO CHAR(18)
        START 18
        TYPE C
        INTERNALNAME PARTINFO
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047';

COMMIT DDL;
