-- !! WARNING: DROP COLUMN is irreversible. Data in PARTNAME will be lost. !!
-- ALTER: Drop PARTNAME and add PARTINFO to PARTROOT in database DI21PART
-- PSB: DFSSAM09 / PCB: PCB01
-- Generated: 2026-09-21 11:36:50

ALTER TABLE PARTROOT IN DATABASE DI21PART
    DROP COLUMN PARTNAME RESTRICT;

COMMIT DDL;

ALTER TABLE PARTROOT IN DATABASE DI21PART
    ADD COLUMN PARTINFO CHAR(12)
        TYPE C
        INTERNALNAME PARTINFO
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047';

COMMIT DDL;
