-- ALTER: Add column PARTNAME to PARTROOT in database DI21PART
-- PSB: DFSSAM09 / PCB: PCB01
-- Generated: 2026-09-21 09:15:40

ALTER TABLE PARTROOT IN DATABASE DI21PART
    ADD COLUMN PARTNAME CHAR(8)
        TYPE C
        INTERNALNAME PARTNAME
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047';

COMMIT DDL;
