-- EDITOR (copybook): Add missing fields to STOKSTAT in DFSSAM09 (DBD: DI21PART)
-- Source copybook: C00SAM09.cpy (01 STOKSTAT)
-- Generated: 2026-07-20 10:46:07
-- Fields skipped (FILLER): FILLER1(XX), FILLER2(X(10)), FILLER3(X(05)),
--                           FILLER4(X(33)), FILLER5(X(15)), FILLER6(X(23))
-- Note: IMS column names are alphanumeric only, max 8 chars
--   SS-UNIT-PRICE    -> SSUNPRC
--   SS-UNIT-OF-MEAS  -> SSUOMEA
--   SS-STOCK-DATE    -> SSSTKDT
--   SS-CUR-REQMTS    -> SSCREQM
--   SS-UNPL-REQMTS   -> SSUREQM
--   SS-ON-ORDER      -> SSONORD
--   SS-IN-STOCK      -> SSINSTK
--   SS-PLAN-DISB     -> SSPLDIS
--   SS-UNPL-DISB     -> SSULDIS

ALTER TABLE STOKSTAT IN DATABASE DI21PART
  ADD COLUMN SSUNPRC CHAR(9)
    START 11
    TYPE C
    INTERNALNAME SSUNPRC
    INTERNAL TYPECONVERTER CHAR
    CCSID 'Cp1047',
  ADD COLUMN SSUOMEA CHAR(4)
    START 20
    TYPE C
    INTERNALNAME SSUOMEA
    INTERNAL TYPECONVERTER CHAR
    CCSID 'Cp1047',
  ADD COLUMN SSSTKDT CHAR(3)
    START 24
    TYPE C
    INTERNALNAME SSSTKDT
    INTERNAL TYPECONVERTER CHAR
    CCSID 'Cp1047',
  ADD COLUMN SSCREQM CHAR(8)
    START 27
    TYPE C
    INTERNALNAME SSCREQM
    INTERNAL TYPECONVERTER CHAR
    CCSID 'Cp1047',
  ADD COLUMN SSUREQM CHAR(8)
    START 35
    TYPE C
    INTERNALNAME SSUREQM
    INTERNAL TYPECONVERTER CHAR
    CCSID 'Cp1047',
  ADD COLUMN SSONORD CHAR(8)
    START 43
    TYPE C
    INTERNALNAME SSONORD
    INTERNAL TYPECONVERTER CHAR
    CCSID 'Cp1047',
  ADD COLUMN SSINSTK CHAR(8)
    START 51
    TYPE C
    INTERNALNAME SSINSTK
    INTERNAL TYPECONVERTER CHAR
    CCSID 'Cp1047',
  ADD COLUMN SSPLDIS CHAR(8)
    START 59
    TYPE C
    INTERNALNAME SSPLDIS
    INTERNAL TYPECONVERTER CHAR
    CCSID 'Cp1047',
  ADD COLUMN SSULDIS CHAR(8)
    START 67
    TYPE C
    INTERNALNAME SSULDIS
    INTERNAL TYPECONVERTER CHAR
    CCSID 'Cp1047';
