CREATE DATABASE DI24PART ACCESS HISAM
    VERSION '09/15/2026.16'
    PASSWDNO
    DATXEXITNO
    DATA CAPTURE NONE CCSID 'Cp1047';

CREATE TABLESPACE DI24PART IN DI24PART
    RECORD(17,17)
    SIZE PRIMARY 2048 SIZE SECONDARY 2048
    OVERFLOW(DI24PARO);

CREATE TABLE PARTROOT (
    PARTKEY CHAR(17)
        START 1
        TYPE C
        INTERNALNAME PARTKEY
        PRIMARY KEY
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047'
    ) IN DATABASE DI24PART
    INTERNALNAME PARTROOT
    MAXBYTES 17
    INSERT LOGICAL DELETE LOGICAL REPLACE LOGICAL
    AMBIGUOUS INSERT LAST
    CCSID 'Cp1047';

CREATE TABLE STOKSTAT (
    STOCKEY CHAR(17)
        START 1
        TYPE C
        INTERNALNAME STOCKEY
        PRIMARY KEY
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    PARTKEY CHAR(17)
        START 18
        TYPE C
        INTERNALNAME PARTKEY
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    FOREIGN KEY (PARTKEY) REFERENCES PARTROOT
    ) IN DATABASE DI24PART
    INTERNALNAME STOKSTAT
    MAXBYTES 34
    INSERT LOGICAL DELETE LOGICAL REPLACE LOGICAL
    AMBIGUOUS INSERT LAST
    CCSID 'Cp1047';
