CREATE DATABASE DI24PART ACCESS DEDB
    RMNAME(DBFDBMA0)
    VERSION '09/08/2026.15'
    DATA CAPTURE NONE CCSID 'Cp1047';

CREATE TABLE PARTROOT (
    PARTKEY CHAR(17)
        START 1
        TYPE C
        INTERNALNAME PARTKEY
        PRIMARY KEY
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    PARTNAME CHAR(12)
        START 18
        TYPE C
        INTERNALNAME PARTNAME
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    PARTDESC CHAR(21)
        START 30
        TYPE C
        INTERNALNAME PARTDESC
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047'
    ) IN DATABASE DI24PART
    INTERNALNAME PARTROOT
    MAXBYTES 50
    CCSID 'Cp1047';

COMMIT DDL;
