CREATE DATABASE DI26PART ACCESS DEDB
    RMNAME(DBFDBMA0)
    VERSION '09/16/2026.13'
    DATA CAPTURE NONE CCSID 'Cp1047';

CREATE TABLESPACE DI26PART IN DI26PART
    SIZE PRIMARY 512
    UOW(100,2)
    ROOT(100,2);

CREATE TABLE PARTROOT (
    PARTKEY CHAR(17)
        START 1
        TYPE C
        INTERNALNAME PARTKEY
        PRIMARY KEY
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047'
    ) IN DATABASE DI26PART
    INTERNALNAME PARTROOT
    MAXBYTES 17
    CCSID 'Cp1047';

CREATE TABLE STOKSTAT (
    STOCKEY CHAR(17)
        START 1
        TYPE C
        INTERNALNAME STOCKEY
        PRIMARY KEY
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    PARTKEY CHAR(17)
        START 18
        TYPE C
        INTERNALNAME PARTKEY
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    FOREIGN KEY REFERENCES PARTROOT
    ) IN DATABASE DI26PART
    INTERNALNAME STOKSTAT
    MAXBYTES 34
    CCSID 'Cp1047';
