CREATE DATABASE HOTELDB ACCESS DEDB
    RMNAME(DBFDBMA0)
    VERSION '09/21/2026.12'
    DATA CAPTURE NONE CCSID 'Cp1047';

CREATE TABLESPACE HOTELDB IN HOTELDB
    SIZE PRIMARY 512
    UOW(100,2)
    ROOT(100,2);

CREATE TABLE HOTELSEG (
    ROOMNUM CHAR(5)
        START 1
        TYPE C
        INTERNALNAME ROOMNUM
        PRIMARY KEY
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    FSTNAME CHAR(12)
        START 6
        TYPE C
        INTERNALNAME FSTNAME
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    LSTNAME CHAR(12)
        START 18
        TYPE C
        INTERNALNAME LSTNAME
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047'
    ) IN DATABASE HOTELDB
    INTERNALNAME HOTELSEG
    MAXBYTES 29
    CCSID 'Cp1047';

COMMIT DDL;
