CREATE DATABASE SCHOOLDB ACCESS DEDB
    RMNAME(DBFDBMA0)
    VERSION '09/21/2026.11'
    DATA CAPTURE NONE CCSID 'Cp1047';

CREATE TABLESPACE SCHOOLDB IN SCHOOLDB
    SIZE PRIMARY 512
    UOW(100,2)
    ROOT(100,2);

CREATE TABLE SCHOOL (
    SCID CHAR(5)
        START 1
        TYPE C
        INTERNALNAME SCID
        PRIMARY KEY
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    SCNAME CHAR(15)
        START 6
        TYPE C
        INTERNALNAME SCNAME
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    SCCOUNTY CHAR(15)
        START 21
        TYPE C
        INTERNALNAME SCCOUNTY
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047'
    ) IN DATABASE SCHOOLDB
    INTERNALNAME SCHOOL
    MAXBYTES 35
    CCSID 'Cp1047';

COMMIT DDL;
