CREATE PROGRAMVIEW AUTPSB11 (
    CREATE SCHEMA AUSI2PCB USING AUTPSB11
        AS AUSI2PCB (
            CREATE SENSEGVIEW SINDXB
        )
        PROCOPT 'AP' LISTYES
        POSSNGL SBCOND,
    CREATE SCHEMA AUTOLPCB USING AUTPSB11
        AS AUTOLPCB (
        )
        PROCOPT 'AP' LISTYES
        POSSNGL SBCOND,
    CREATE SCHEMA AUTS1PCB USING AUTPSB11
        AS AUTS1PCB (
        )
        PROCOPT 'AP' LISTYES
        POSSNGL SBCOND,
    CREATE SCHEMA AUTS2PCB USING AUTPSB11
        AS AUTS2PCB (
        )
        PROCOPT 'AP' LISTYES
        POSSNGL SBCOND,
    CREATE SCHEMA EMPLPCB USING AUTPSB11
        AS EMPLPCB (
        )
        PROCOPT 'AP' LISTYES
        POSSNGL SBCOND
) CMPATYES GSROLBOKNO OLICYES LOCKMAX 0 IOASIZE 600 SSASIZE 840
    LANGASSEM;

COMMIT DDL;
