CREATE PROGRAMVIEW DI24PSB (
    CREATE SCHEMA PCB01 USING DI24PART
        AS PCB01 (
            CREATE SENSEGVIEW PARTROOT)
        PROCOPT 'AP' LISTYES
        POSSNGL SBCOND
) CMPATYES GSROLBOKNO OLICYES LOCKMAX 0 IOASIZE 600 SSASIZE 840
    LANGASSEM;

COMMIT DDL;
