CREATE PROGRAMVIEW DI25PSB (
    CREATE SCHEMA PCB01 USING DI25PART
        AS PCB01 (
            CREATE SENSEGVIEW PARTROOT,
            CREATE SENSEGVIEW STOKSTAT)
        PROCOPT 'AP' LISTYES
        POSSNGL SBCOND
) CMPATYES GSROLBOKNO OLICYES LOCKMAX 0 IOASIZE 600 SSASIZE 840
    LANGASSEM;

COMMIT DDL;
