CREATE PROGRAMVIEW HOTELPSB (
    CREATE SCHEMA HOTELPCB USING HOTELDB
        AS HOTELPCB (
            CREATE SENSEGVIEW HOTELSEG)
        PROCOPT 'AP' LISTYES
        POSSNGL SBCOND
) CMPATYES GSROLBOKNO OLICYES LOCKMAX 0 IOASIZE 600 SSASIZE 840
    LANGASSEM;

COMMIT DDL;
