package com.ibm.ims.jdbcbob;

import com.ibm.ims.jdbc.IMSDataSource;

import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * IMSCatalogDDLExporter — Generated by Bob for Z
 *
 * Connects to each PSB in the IMS Catalog via JDBC and reconstructs DDL
 * for every PSB (CREATE PROGRAMVIEW) and every underlying DBD (CREATE DATABASE)
 * using DatabaseMetaData: schemas → PCBs, tables → segments, columns → fields.
 *
 * Output structure:
 *   catalog-export/psb/<PSBNAME>.ddl   — one PSB DDL file per program view
 *   catalog-export/dbd/<DBDNAME>.ddl   — one DBD DDL file per database (deduplicated)
 *   catalog-export/export.log          — run summary with counts and errors
 *
 * Usage:
 *   mvn exec:java -Dexec.mainClass="com.ibm.ims.jdbcbob.IMSCatalogDDLExporter"
 *
 * Exit codes:
 *   0 = All DDL exported successfully
 *   1 = Partial export (some PSBs failed — see export.log)
 *   2 = Fatal setup error
 */
public class IMSCatalogDDLExporter {

    private static final String HOST     = IMSConnectionConfig.HOST;
    private static final int    PORT     = IMSConnectionConfig.PORT;
    private static final String USER     = IMSConnectionConfig.USER;
    private static final String PASSWORD = IMSConnectionConfig.PASSWORD;

    private static final String OUTPUT_ROOT = "../catalog-export";
    private static final String PSB_DIR     = OUTPUT_ROOT + "/psb";
    private static final String DBD_DIR     = OUTPUT_ROOT + "/dbd";
    private static final String LOG_FILE    = OUTPUT_ROOT + "/export.log";

    // Full PSB list from IMS Catalog
    private static final String[] PSB_NAMES = {
        "DFSSAMT4",
        "DFSSAM01", "DFSSAM02", "DFSSAM03", "DFSSAM04", "DFSSAM05",
        "DFSSAM06", "DFSSAM07", "DFSSAM08", "DFSSAM09",
        "DHHOSPSB",
        "IPOPSB", "IPOPSBL",
        "JBPLAB", "JBPPARTS", "JMPPARTS",
        "URSOPRTS"
    };

    public static void main(String[] args) {
        String timestamp = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss").format(new Date());

        System.out.println("=".repeat(72));
        System.out.println("IMS Catalog DDL Exporter — Generated by Bob for Z");
        System.out.println("=".repeat(72));
        System.out.println("Host   : " + HOST + ":" + PORT);
        System.out.println("PSBs   : " + PSB_NAMES.length);
        System.out.println("Output : " + new File(OUTPUT_ROOT).getAbsolutePath());
        System.out.println("Start  : " + timestamp);
        System.out.println("=".repeat(72));
        System.out.println();

        ensureDir(PSB_DIR);
        ensureDir(DBD_DIR);

        int psbSuccess = 0, psbFail = 0;
        List<String> errors = new ArrayList<>();
        // Track DBD DDLs across PSBs to deduplicate — key = DBD name, value = DDL text
        Map<String, String> dbdDdlMap = new LinkedHashMap<>();

        try (PrintWriter log = new PrintWriter(new FileWriter(LOG_FILE, false))) {

            log.println("IMS Catalog DDL Export — " + timestamp);
            log.println("Host: " + HOST + ":" + PORT);
            log.println("=".repeat(72));

            for (String psbName : PSB_NAMES) {
                System.out.print("  " + psbName + " ... ");
                try {
                    // Connect to this PSB
                    IMSDataSource ds = new IMSDataSource();
                    ds.setHost(HOST);
                    ds.setPortNumber(PORT);
                    ds.setDriverType(4);
                    ds.setUser(USER);
                    ds.setPassword(PASSWORD);
                    ds.setDatabaseName(psbName);

                    try (Connection conn = ds.getConnection()) {
                        DatabaseMetaData dbmd = conn.getMetaData();

                        // Collect PCBs → tables → columns
                        // pcbTables: pcbName → ordered list of table names
                        Map<String, List<String>> pcbTables = new LinkedHashMap<>();
                        // tableColumns: tableName → ordered list of ColumnInfo
                        Map<String, List<ColumnInfo>> tableColumns = new LinkedHashMap<>();
                        // pcbDbdName: pcbName → catalog (DBD name)
                        Map<String, String> pcbDbdName = new LinkedHashMap<>();

                        // Step 1: enumerate PCBs (schemas)
                        ResultSet schemas = dbmd.getSchemas(psbName, null);
                        while (schemas.next()) {
                            String pcb    = schemas.getString("TABLE_SCHEM");
                            String catalog = schemas.getString("TABLE_CATALOG");
                            if (pcb == null) continue;
                            pcbTables.put(pcb.trim(), new ArrayList<>());
                            if (catalog != null) pcbDbdName.put(pcb.trim(), catalog.trim());
                        }
                        schemas.close();

                        // Step 2: enumerate tables per PCB
                        ResultSet tables = dbmd.getTables(psbName, null, null, null);
                        while (tables.next()) {
                            String pcb   = tables.getString("TABLE_SCHEM");
                            String table = tables.getString("TABLE_NAME");
                            if (pcb == null || table == null) continue;
                            pcbTables.computeIfAbsent(pcb.trim(), k -> new ArrayList<>())
                                     .add(table.trim());
                        }
                        tables.close();

                        // Step 3: enumerate columns per table
                        ResultSet cols = dbmd.getColumns(psbName, null, null, null);
                        while (cols.next()) {
                            String pcb      = cols.getString("TABLE_SCHEM");
                            String table    = cols.getString("TABLE_NAME");
                            String colName  = cols.getString("COLUMN_NAME");
                            String typeName = cols.getString("TYPE_NAME");
                            int    colSize  = cols.getInt("COLUMN_SIZE");
                            int    ordinal  = cols.getInt("ORDINAL_POSITION");
                            if (table == null || colName == null) continue;
                            String key = (pcb != null ? pcb.trim() + "." : "") + table.trim();
                            tableColumns.computeIfAbsent(key, k -> new ArrayList<>())
                                        .add(new ColumnInfo(colName.trim(),
                                             typeName != null ? typeName.trim() : "CHAR",
                                             colSize, ordinal));
                        }
                        cols.close();

                        // Also try getPrimaryKeys to mark key fields
                        Set<String> primaryKeys = new LinkedHashSet<>();
                        for (Map.Entry<String, List<String>> pcbEntry : pcbTables.entrySet()) {
                            String pcb = pcbEntry.getKey();
                            for (String table : pcbEntry.getValue()) {
                                try {
                                    ResultSet pks = dbmd.getPrimaryKeys(psbName, pcb, table);
                                    while (pks.next()) {
                                        String pkCol = pks.getString("COLUMN_NAME");
                                        if (pkCol != null)
                                            primaryKeys.add(pcb + "." + table + "." + pkCol.trim());
                                    }
                                    pks.close();
                                } catch (Exception ignored) {}
                            }
                        }

                        // --------------------------------------------------------
                        // Generate PSB DDL (CREATE PROGRAMVIEW)
                        // --------------------------------------------------------
                        String psbDdl = buildPsbDdl(psbName, pcbTables, pcbDbdName);
                        writeFile(PSB_DIR + "/" + psbName + ".ddl", psbDdl);

                        // --------------------------------------------------------
                        // Generate DBD DDL stubs (CREATE DATABASE / TABLE)
                        // for each DBD referenced by this PSB (deduplicated)
                        // --------------------------------------------------------
                        for (Map.Entry<String, List<String>> pcbEntry : pcbTables.entrySet()) {
                            String pcb    = pcbEntry.getKey();
                            String dbdName = pcbDbdName.getOrDefault(pcb, null);
                            if (dbdName == null || dbdDdlMap.containsKey(dbdName)) continue;

                            String dbdDdl = buildDbdDdl(dbdName, pcbEntry.getValue(),
                                                         pcb, tableColumns, primaryKeys);
                            dbdDdlMap.put(dbdName, dbdDdl);
                        }
                    }

                    System.out.println("✓");
                    log.println("  OK  " + psbName);
                    psbSuccess++;

                } catch (Exception e) {
                    System.out.println("✗  " + e.getMessage());
                    log.println("  ERR " + psbName + ": " + e.getMessage());
                    errors.add(psbName + ": " + e.getMessage());
                    psbFail++;
                }
            }

            // Write all deduplicated DBD DDL files
            System.out.println();
            System.out.println("--- Writing DBD DDL files ---");
            for (Map.Entry<String, String> entry : dbdDdlMap.entrySet()) {
                writeFile(DBD_DIR + "/" + entry.getKey() + ".ddl", entry.getValue());
                System.out.println("  ✓ " + entry.getKey());
                log.println("  DBD " + entry.getKey());
            }

            // Summary
            System.out.println();
            System.out.println("=".repeat(72));
            System.out.printf("PSB: %d exported, %d failed%n", psbSuccess, psbFail);
            System.out.printf("DBD: %d unique databases written%n", dbdDdlMap.size());
            System.out.println("Log: " + new File(LOG_FILE).getAbsolutePath());
            System.out.println("=".repeat(72));

            log.println("\n[SUMMARY]");
            log.printf("PSB: %d exported, %d failed%n", psbSuccess, psbFail);
            log.printf("DBD: %d unique databases written%n", dbdDdlMap.size());
            if (!errors.isEmpty()) {
                log.println("\n[ERRORS]");
                errors.forEach(log::println);
            }

            System.exit((psbFail > 0) ? 1 : 0);

        } catch (Exception e) {
            System.err.println("✗ Fatal error: " + e.getMessage());
            e.printStackTrace();
            System.exit(2);
        }
    }

    // -------------------------------------------------------------------------
    // DDL builders
    // -------------------------------------------------------------------------

    /**
     * Builds CREATE PROGRAMVIEW DDL for a PSB.
     * One SCHEMA block per PCB, one SENSEGVIEW line per sensitive segment.
     */
    private static String buildPsbDdl(String psbName,
                                       Map<String, List<String>> pcbTables,
                                       Map<String, String> pcbDbdName) {
        StringBuilder sb = new StringBuilder();
        sb.append("CREATE PROGRAMVIEW ").append(psbName).append(" (\n");

        boolean firstPcb = true;
        for (Map.Entry<String, List<String>> entry : pcbTables.entrySet()) {
            String pcb    = entry.getKey();
            String dbdName = pcbDbdName.getOrDefault(pcb, pcb);
            List<String> tables = entry.getValue();

            if (!firstPcb) sb.append(",\n");
            firstPcb = false;

            sb.append("    CREATE SCHEMA ").append(pcb)
              .append(" USING ").append(dbdName).append("\n");
            sb.append("        AS ").append(pcb).append(" (\n");

            for (int i = 0; i < tables.size(); i++) {
                sb.append("            CREATE SENSEGVIEW ").append(tables.get(i));
                if (i < tables.size() - 1) sb.append(",");
                sb.append("\n");
            }

            sb.append("        )\n");
            sb.append("        PROCOPT 'AP' LISTYES\n");
            sb.append("        POSSNGL SBCOND");
        }

        sb.append("\n) CMPATYES GSROLBOKNO OLICYES LOCKMAX 0 IOASIZE 600 SSASIZE 840\n");
        sb.append("    LANGASSEM;\n\n");
        sb.append("COMMIT DDL;\n");
        return sb.toString();
    }

    /**
     * Builds CREATE DATABASE / TABLESPACE / TABLE DDL for a DBD
     * reconstructed from JDBC column metadata.
     */
    private static String buildDbdDdl(String dbdName,
                                       List<String> tables,
                                       String pcb,
                                       Map<String, List<ColumnInfo>> tableColumns,
                                       Set<String> primaryKeys) {
        StringBuilder sb = new StringBuilder();
        sb.append("CREATE DATABASE ").append(dbdName).append(" ACCESS HISAM\n");
        sb.append("    PASSWDNO\n");
        sb.append("    DATXEXITNO\n");
        sb.append("    DATA CAPTURE NONE CCSID 'Cp1047';\n\n");

        sb.append("CREATE TABLESPACE ").append(dbdName).append(" IN ").append(dbdName).append("\n");
        sb.append("    OVERFLOW(").append(abbrev(dbdName)).append("O);\n\n");

        boolean firstTable = true;
        String prevTable = null;

        for (String table : tables) {
            String key = pcb + "." + table;
            List<ColumnInfo> cols = tableColumns.getOrDefault(key, new ArrayList<>());
            cols.sort((a, b) -> Integer.compare(a.ordinal, b.ordinal));

            sb.append("CREATE TABLE ").append(table).append(" (\n");

            for (int i = 0; i < cols.size(); i++) {
                ColumnInfo col = cols.get(i);
                boolean isPk = primaryKeys.contains(pcb + "." + table + "." + col.name);
                int start = computeStart(cols, i);

                sb.append("    ").append(col.name)
                  .append(" ").append(col.typeName).append("(").append(col.size).append(")\n");
                sb.append("        START ").append(start).append("\n");
                sb.append("        TYPE C\n");
                sb.append("        INTERNALNAME ").append(col.name).append("\n");
                if (isPk) sb.append("        PRIMARY KEY\n");
                sb.append("        INTERNAL TYPECONVERTER CHAR\n");
                sb.append("        CCSID 'Cp1047'");
                if (i < cols.size() - 1) sb.append(",");
                sb.append("\n");
            }

            // FK to previous table (parent segment)
            if (!firstTable && prevTable != null && cols.isEmpty()) {
                sb.append("    FOREIGN KEY REFERENCES ").append(prevTable).append("\n");
            } else if (!firstTable && prevTable != null) {
                // append FK after last column
                int lastIdx = sb.lastIndexOf("\n");
                sb.insert(lastIdx + 1, "    FOREIGN KEY REFERENCES " + prevTable + "\n");
            }

            sb.append("    ) IN DATABASE ").append(dbdName).append("\n");
            sb.append("    INTERNALNAME ").append(table).append("\n");
            sb.append("    INSERT LOGICAL DELETE LOGICAL REPLACE LOGICAL\n");
            sb.append("    AMBIGUOUS INSERT LAST\n");
            sb.append("    CCSID 'Cp1047';\n\n");

            prevTable = firstTable ? table : prevTable;
            firstTable = false;
        }

        sb.append("COMMIT DDL;\n");
        return sb.toString();
    }

    /** Computes column start position from sum of preceding column sizes. */
    private static int computeStart(List<ColumnInfo> cols, int idx) {
        int pos = 1;
        for (int i = 0; i < idx; i++) pos += cols.get(i).size;
        return pos;
    }

    /** Returns an 8-char abbreviation of a dataset name for overflow DD names. */
    private static String abbrev(String name) {
        return name.length() > 7 ? name.substring(0, 7) : name;
    }

    // -------------------------------------------------------------------------
    // Utilities
    // -------------------------------------------------------------------------

    private static void writeFile(String path, String content) throws Exception {
        File f = new File(path);
        f.getParentFile().mkdirs();
        try (PrintWriter pw = new PrintWriter(new FileWriter(f, false))) {
            pw.print(content);
        }
    }

    private static void ensureDir(String path) {
        new File(path).mkdirs();
    }

    // -------------------------------------------------------------------------
    // Inner types
    // -------------------------------------------------------------------------

    private static class ColumnInfo {
        final String name;
        final String typeName;
        final int    size;
        final int    ordinal;

        ColumnInfo(String name, String typeName, int size, int ordinal) {
            this.name     = name;
            this.typeName = typeName;
            this.size     = size;
            this.ordinal  = ordinal;
        }
    }
}
