package com.ibm.ims.jdbcbob;

/**
 * IMS Connection Configuration — Generated by Bob for Z
 *
 * Central configuration for all IMS JDBC connections.
 * Update this file to switch between IMS systems without touching any other program.
 *
 * All executor programs (IMSQueryExecutor, IMSDBAExecutor, IMSMetadataExplorer, etc.)
 * read their connection properties from here at runtime.
 */
public class IMSConnectionConfig {

    // -------------------------------------------------------------------------
    // IMS Type-4 JDBC connection properties
    // Update these values to target a different IMS system.
    // -------------------------------------------------------------------------

    /** Hostname or IP address of the IMS Connect server */
    public static final String HOST = "172.19.3.3";

    /** Port number of the IMS Connect server */
    public static final int PORT = 5555;

    /** RACF user ID */
    public static final String USER = "IBMUSER";

    /** RACF password */
    public static final String PASSWORD = "tumpy2";

    // -------------------------------------------------------------------------
    // DDL-specific properties (used by IMSDBAExecutor only)
    // -------------------------------------------------------------------------

    /**
     * PSB name used for DDL operations.
     * Must be DFSCP001 for DDL authorization on most IMS regions.
     */
    public static final String DDL_PSB = "DFSCP001";

    // Private constructor — this is a static config class, not instantiated.
    private IMSConnectionConfig() {}
}
