package com.ibm.ims.jdbcbob;

import com.ibm.ims.jdbc.IMSDataSource;
import java.io.File;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Universal IMS Query Executor
 * Generated by Bob for Z - Single reusable program for all IMS queries
 * 
 * Usage: java IMSQueryExecutor "<database>" "<sql_query>"
 * Example: java IMSQueryExecutor "DFSIVP37" "SELECT * FROM IVPCB.CUSTOMER WHERE LASTNAME = 'last1'"
 */
public class IMSQueryExecutor {
    private static final String RESULTS_DIR = "query_results";
    private static final String HOST     = IMSConnectionConfig.HOST;
    private static final int    PORT     = IMSConnectionConfig.PORT;
    private static final String USER     = IMSConnectionConfig.USER;
    private static final String PASSWORD = IMSConnectionConfig.PASSWORD;
    
    public static void main(String[] args) {
        // Validate arguments
        if (args.length < 2) {
            System.err.println("Usage: java IMSQueryExecutor <database> <sql_query>");
            System.err.println("Example: java IMSQueryExecutor \"DFSIVP37\" \"SELECT * FROM IVPCB.CUSTOMER WHERE LASTNAME = 'last1'\"");
            System.exit(1);
        }
        
        String databaseName = args[0];
        String sqlQuery = args[1];
        
        Connection connection = null;
        Statement statement = null;
        ResultSet resultSet = null;
        PrintWriter csvWriter = null;
        
        try {
            // Create results directory if it doesn't exist
            File resultsDir = new File(RESULTS_DIR);
            if (!resultsDir.exists()) {
                resultsDir.mkdirs();
                System.out.println("Created results directory: " + resultsDir.getAbsolutePath());
            }
            
            // Generate timestamped filename for CSV export
            String timestamp = new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date());
            String csvFilename = RESULTS_DIR + "/" + databaseName + "_query_" + timestamp + ".csv";
            csvWriter = new PrintWriter(new FileWriter(csvFilename));
            
            System.out.println("=".repeat(80));
            System.out.println("IMS Query Executor - Generated by Bob for Z");
            System.out.println("=".repeat(80));
            System.out.println("Database: " + databaseName);
            System.out.println("Query: " + sqlQuery);
            System.out.println("Timestamp: " + new Date());
            System.out.println("=".repeat(80));
            System.out.println();
            
            System.out.println("Connecting to IMS database " + databaseName + "...");
            
            // Create IMS connection
            IMSDataSource ds = new IMSDataSource();
            ds.setHost(HOST);
            ds.setPortNumber(PORT);
            ds.setDriverType(4);
            ds.setUser(USER);
            ds.setPassword(PASSWORD);
            ds.setDatabaseName(databaseName);
            connection = ds.getConnection();
            
            System.out.println("✓ Connected successfully!");
            System.out.println();
            
            // Execute query
            System.out.println("Executing query...");
            statement = connection.createStatement();
            resultSet = statement.executeQuery(sqlQuery);
            
            // Get metadata
            ResultSetMetaData rsmd = resultSet.getMetaData();
            int columnCount = rsmd.getColumnCount();
            
            // Write CSV metadata header
            csvWriter.println("# Database: " + databaseName);
            csvWriter.println("# Query: " + sqlQuery);
            csvWriter.println("# Timestamp: " + new Date());
            csvWriter.println("# User: " + USER);
            csvWriter.println();
            
            // Write CSV column headers
            for (int i = 1; i <= columnCount; i++) {
                csvWriter.print(rsmd.getColumnName(i));
                if (i < columnCount) {
                    csvWriter.print(",");
                }
            }
            csvWriter.println();
            
            // Display column headers to console
            System.out.println("=== Query Results ===");
            for (int i = 1; i <= columnCount; i++) {
                System.out.print(rsmd.getColumnName(i));
                if (i < columnCount) {
                    System.out.print(" | ");
                }
            }
            System.out.println();
            System.out.println("-".repeat(80));
            
            // Process and display all records
            int recordCount = 0;
            while (resultSet.next()) {
                recordCount++;
                System.out.println("\nRecord #" + recordCount + ":");
                
                // Write to CSV and display to console
                for (int i = 1; i <= columnCount; i++) {
                    String columnName = rsmd.getColumnName(i);
                    String value = resultSet.getString(i);
                    String displayValue = (value != null ? value.trim() : "NULL");
                    
                    // Display to console
                    System.out.println("  " + columnName + ": " + displayValue);
                    
                    // Write to CSV (escape commas and quotes)
                    if (value != null) {
                        value = value.trim();
                        // Escape quotes and wrap in quotes if contains comma
                        if (value.contains(",") || value.contains("\"") || value.contains("\n")) {
                            value = "\"" + value.replace("\"", "\"\"") + "\"";
                        }
                        csvWriter.print(value);
                    }
                    
                    if (i < columnCount) {
                        csvWriter.print(",");
                    }
                }
                csvWriter.println();
            }
            
            System.out.println("\n" + "=".repeat(80));
            System.out.println("✓ Query completed successfully!");
            System.out.println("Total records retrieved: " + recordCount);
            System.out.println("Results saved to: " + new File(csvFilename).getAbsolutePath());
            System.out.println("=".repeat(80));
            
            // Commit and close connection
            connection.commit();
            
        } catch (Exception e) {
            System.err.println("\n" + "=".repeat(80));
            System.err.println("✗ Error occurred while executing query:");
            System.err.println("=".repeat(80));
            System.err.println("Error message: " + e.getMessage());
            System.err.println();
            System.err.println("Troubleshooting tips:");
            System.err.println("1. Verify the PCB name exists in the database");
            System.err.println("2. Check that the table/segment name is correct");
            System.err.println("3. Ensure you have proper access permissions");
            System.err.println("4. Validate the SQL syntax for IMS");
            System.err.println("=".repeat(80));
            e.printStackTrace();
            System.exit(1);
            
        } finally {
            // Clean up resources
            try {
                if (csvWriter != null) {
                    csvWriter.close();
                    System.out.println("CSV file closed and saved.");
                }
                if (resultSet != null) resultSet.close();
                if (statement != null) statement.close();
                if (connection != null) connection.close();
                System.out.println("Database connection closed.");
            } catch (Exception e) {
                System.err.println("Error closing resources: " + e.getMessage());
            }
        }
    }
}
