CREATE PROGRAMVIEW DFSIVP37 (
    CREATE SCHEMA PHONEAP USING DFSIVP37
        AS PHONEAP (
            CREATE SENSEGVIEW PHONEBOOK
        )
        PROCOPT 'AP' LISTYES
        POSSNGL SBCOND
) CMPATYES GSROLBOKNO OLICYES LOCKMAX 0 IOASIZE 600 SSASIZE 840
    LANGASSEM;

COMMIT DDL;
