CREATE PROGRAMVIEW DFSIVP1 (
    CREATE SCHEMA PCB01 USING DFSIVP1
        AS PCB01 (
            CREATE SENSEGVIEW A1111111
        )
        PROCOPT 'AP' LISTYES
        POSSNGL SBCOND
) CMPATYES GSROLBOKNO OLICYES LOCKMAX 0 IOASIZE 600 SSASIZE 840
    LANGASSEM;

COMMIT DDL;
