CREATE PROGRAMVIEW DFSSAM02 (
    CREATE SCHEMA DBPCB01 USING DFSSAM02
        AS DBPCB01 (
            CREATE SENSEGVIEW PARTROOT,
            CREATE SENSEGVIEW STANINFO
        )
        PROCOPT 'AP' LISTYES
        POSSNGL SBCOND
) CMPATYES GSROLBOKNO OLICYES LOCKMAX 0 IOASIZE 600 SSASIZE 840
    LANGASSEM;

COMMIT DDL;
