CREATE PROGRAMVIEW DFSSAM07 (
    CREATE SCHEMA DBPCB01 USING DFSSAM07
        AS DBPCB01 (
            CREATE SENSEGVIEW BACKORDR,
            CREATE SENSEGVIEW CYCCOUNT,
            CREATE SENSEGVIEW PARTROOT,
            CREATE SENSEGVIEW STANINFO,
            CREATE SENSEGVIEW STOKSTAT
        )
        PROCOPT 'AP' LISTYES
        POSSNGL SBCOND
) CMPATYES GSROLBOKNO OLICYES LOCKMAX 0 IOASIZE 600 SSASIZE 840
    LANGASSEM;

COMMIT DDL;
