CREATE PROGRAMVIEW DFSSAM09 (
    CREATE SCHEMA PCB01 USING DFSSAM09
        AS PCB01 (
            CREATE SENSEGVIEW BACKORDR,
            CREATE SENSEGVIEW CYCCOUNT,
            CREATE SENSEGVIEW PARTROOT,
            CREATE SENSEGVIEW STANINFO,
            CREATE SENSEGVIEW STOKSTAT
        )
        PROCOPT 'AP' LISTYES
        POSSNGL SBCOND
) CMPATYES GSROLBOKNO OLICYES LOCKMAX 0 IOASIZE 600 SSASIZE 840
    LANGASSEM;

COMMIT DDL;
