CREATE PROGRAMVIEW IPOPSB (
    CREATE SCHEMA IPOPCB USING IPOPSB
        AS IPOPCB (
            CREATE SENSEGVIEW ITEM,
            CREATE SENSEGVIEW ORDER_TBL
        )
        PROCOPT 'AP' LISTYES
        POSSNGL SBCOND
) CMPATYES GSROLBOKNO OLICYES LOCKMAX 0 IOASIZE 600 SSASIZE 840
    LANGASSEM;

COMMIT DDL;
