CREATE PROGRAMVIEW URSOPRTS (
    CREATE SCHEMA DBPCB02 USING URSOPRTS
        AS DBPCB02 (
            CREATE SENSEGVIEW BACKORDR,
            CREATE SENSEGVIEW CYCCOUNT,
            CREATE SENSEGVIEW PARTROOT,
            CREATE SENSEGVIEW STANINFO,
            CREATE SENSEGVIEW STOKSTAT
        )
        PROCOPT 'AP' LISTYES
        POSSNGL SBCOND
) CMPATYES GSROLBOKNO OLICYES LOCKMAX 0 IOASIZE 600 SSASIZE 840
    LANGASSEM;

COMMIT DDL;
