CREATE DATABASE AUTODB ACCESS HDAM OSAM
    RMNAME(DFSHDC40 RMANCH 1 RMRBN 5 RMBYTES 200)
    VERSION '01/04/1814.58'
    DATA CAPTURE NONE DATXEXITNO
    CCSID 'Cp1047';

CREATE TABLESPACE DFSDLR IN AUTODB
    SIZE PRIMARY 1690
    SCAN 3;

CREATE TABLE DEALER (
    DLRNO CHAR(4)
        START 1
        TYPE C
        INTERNALNAME DLRNO
        PRIMARY KEY
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    DLRNAME CHAR(30)
        START 5
        TYPE C
        INTERNALNAME DLRNAME
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    CITY CHAR(10)
        START 35
        TYPE C
        INTERNALNAME CITY
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    ZIP CHAR(10)
        START 45
        TYPE C
        INTERNALNAME ZIP
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    PHONE CHAR(7)
        START 55
        TYPE C
        INTERNALNAME PHONE
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    LCHILD SINDEX22.SINDXB
        INDEX
        AMBIGUOUS INSERT LAST,
    XDFLD XFLD2 SEGMENT MODEL
        SRCH(MAKE,MODEL)
        SUBSEQ(YEAR,"/SX1")
        DDATA(COUNT)
    ) IN AUTODB.DFSDLR
    INTERNALNAME DEALER
    MAXBYTES 61
    TWIN
    INSERT LOGICAL DELETE LOGICAL REPLACE LOGICAL
    AMBIGUOUS INSERT LAST
    CCSID 'Cp1047';

CREATE TABLE MODEL (
    MODKEY CHAR(24)
        START 3
        TYPE C
        INTERNALNAME MODKEY
        PRIMARY KEY
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    MODTYPE CHAR(2)
        START 1
        TYPE C
        INTERNALNAME MODTYPE
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    MAKE CHAR(10)
        START 3
        TYPE C
        INTERNALNAME MAKE
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    MODEL CHAR(10)
        START 13
        TYPE C
        INTERNALNAME MODEL
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    YEAR CHAR(4)
        START 23
        TYPE C
        INTERNALNAME YEAR
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    MSRP BINARY BYTES 5
        START 27
        TYPE P
        INTERNALNAME MSRP
        INTERNAL TYPECONVERTER BINARY,
    COUNT_COL BINARY BYTES 2
        START 32
        TYPE P
        INTERNALNAME COUNT
        INTERNAL TYPECONVERTER BINARY,
    "/SX1" CHAR BYTES 4
        START 1
        INTERNALNAME "/SX1",
    FOREIGN KEY REFERENCES DEALER SINGLE
    ) IN AUTODB.DFSDLR
    INTERNALNAME MODEL
    MAXBYTES 37
    TWIN
    INSERT LOGICAL DELETE LOGICAL REPLACE LOGICAL
    AMBIGUOUS INSERT LAST
    CCSID 'Cp1047';

CREATE TABLE ORDER_TBL (
    ORDNBR CHAR(6)
        START 1
        TYPE C
        INTERNALNAME ORDNBR
        PRIMARY KEY
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    LASTNME CHAR(25)
        START 7
        TYPE C
        INTERNALNAME LASTNME
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    FIRSTNME CHAR(25)
        START 32
        TYPE C
        INTERNALNAME FIRSTNME
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    DATE CHAR(10)
        START 57
        TYPE C
        INTERNALNAME DATE
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    TIME CHAR(8)
        START 67
        TYPE C
        INTERNALNAME TIME
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    LCHILD SINDEX11.SINDXA
        INDEX,
    XDFLD XFLD1 SEGMENT ORDER
        SRCH(LASTNME,FIRSTNME,ORDNBR)
        DDATA(DATE),
    FOREIGN KEY REFERENCES MODEL SINGLE
    ) IN AUTODB.DFSDLR
    INTERNALNAME ORDER
    MAXBYTES 74
    TWIN
    INSERT LOGICAL DELETE LOGICAL REPLACE LOGICAL
    AMBIGUOUS INSERT LAST
    CCSID 'Cp1047';

CREATE TABLE SALES (
    SALENUM CHAR(4)
        START 49
        TYPE C
        INTERNALNAME SALENUM
        PRIMARY KEY
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    SALDATE CHAR(8)
        START 53
        TYPE C
        INTERNALNAME SALDATE
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    LASTNME CHAR(25)
        START 61
        TYPE C
        INTERNALNAME LASTNME
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    FOREIGN KEY REFERENCES MODEL SINGLE
    ) IN AUTODB.DFSDLR
    INTERNALNAME SALES
    MAXBYTES 85
    LPARENT STOCK PHYSICAL
    TWINBWD LTWINBWD LPARNTYES
    INSERT VIRTUAL DELETE VIRTUAL REPLACE VIRTUAL
    AMBIGUOUS INSERT LAST
    CCSID 'Cp1047';

CREATE TABLE STOCK (
    STKVIN CHAR(20)
        START 1
        TYPE C
        INTERNALNAME STKVIN
        PRIMARY KEY
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    COLOR CHAR(10)
        START 21
        TYPE C
        INTERNALNAME COLOR
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    PRICE CHAR(5)
        START 31
        TYPE C
        INTERNALNAME PRICE
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    LOT CHAR(10)
        START 36
        TYPE C
        INTERNALNAME LOT
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    WRNTY BINARY BYTES 1
        START 46
        TYPE X
        INTERNALNAME WRNTY
        INTERNAL TYPECONVERTER BINARY,
    LCHILD SALES
        DOUBLE
        PAIR STOCSALE
        AMBIGUOUS INSERT LAST,
    FOREIGN KEY REFERENCES MODEL SINGLE
    ) IN AUTODB.DFSDLR
    INTERNALNAME STOCK
    MAXBYTES 46
    TWIN
    INSERT LOGICAL DELETE LOGICAL REPLACE LOGICAL
    AMBIGUOUS INSERT LAST
    CCSID 'Cp1047';

CREATE TABLE STOCSALE (
    DLRNO CHAR(4)
        START 1
        TYPE C
        INTERNALNAME DLRNO
        PRIMARY KEY
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    SALENUM CHAR(4)
        START 29
        TYPE C
        INTERNALNAME SALENUM
        PRIMARY KEY
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    MODKEY CHAR(24)
        START 5
        TYPE C
        INTERNALNAME MODKEY
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    SALDATE CHAR(8)
        START 33
        TYPE C
        INTERNALNAME SALDATE
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    LASTNME CHAR(25)
        START 41
        TYPE C
        INTERNALNAME LASTNME
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    FOREIGN KEY REFERENCES STOCK SINGLE
    ) IN AUTODB.DFSDLR
    INTERNALNAME STOCSALE
    SOURCE(AUTODB.SALES DATA)
    PAIREDYES
    CCSID 'Cp1047';

CREATE TABLE SALESPER (
    EMPNO CHAR(6)
        START 1
        TYPE C
        INTERNALNAME EMPNO
        PRIMARY KEY
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    FOREIGN KEY REFERENCES DEALER SINGLE
    ) IN AUTODB.DFSDLR
    INTERNALNAME SALESPER
    MAXBYTES 6
    LPARENT EMPDB2.EMPL PHYSICAL
    TWINBWD LTWINBWD LPARNTYES
    INSERT VIRTUAL DELETE VIRTUAL REPLACE VIRTUAL
    AMBIGUOUS INSERT LAST
    CCSID 'Cp1047';

CREATE TABLE SALESINF (
    QUOTA CHAR(5)
        START 1
        TYPE C
        INTERNALNAME QUOTA
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    SALESYTD CHAR(5)
        START 6
        TYPE C
        INTERNALNAME SALESYTD
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    COMSSION CHAR(5)
        START 11
        TYPE C
        INTERNALNAME COMSSION
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    FOREIGN KEY REFERENCES SALESPER SINGLE
    ) IN AUTODB.DFSDLR
    INTERNALNAME SALESINF
    MAXBYTES 15
    TWIN
    INSERT LOGICAL DELETE LOGICAL REPLACE LOGICAL
    AMBIGUOUS INSERT LAST
    CCSID 'Cp1047';


COMMIT;