CREATE DATABASE AUTOLDB ACCESS LOGICAL
    VERSION '01/11/1814.19'
    CCSID 'Cp1047';

CREATE TABLE DEALER
    IN DATABASE AUTOLDB
    INTERNALNAME DEALER
    SOURCE(AUTODB.DEALER DATA)
    CCSID 'Cp1047';

CREATE TABLE MODEL (
    FOREIGN KEY REFERENCES DEALER
    ) IN DATABASE AUTOLDB
    INTERNALNAME MODEL
    SOURCE(AUTODB.MODEL DATA)
    CCSID 'Cp1047';

CREATE TABLE ORDER_TBL (
    FOREIGN KEY REFERENCES MODEL
    ) IN DATABASE AUTOLDB
    INTERNALNAME ORDER
    SOURCE(AUTODB.ORDER DATA)
    CCSID 'Cp1047';

CREATE TABLE SALES (
    FOREIGN KEY REFERENCES MODEL
    ) IN DATABASE AUTOLDB
    INTERNALNAME SALES
    SOURCE(AUTODB.SALES DATA, AUTODB.STOCK DATA)
    CCSID 'Cp1047';

CREATE TABLE STOCK (
    FOREIGN KEY REFERENCES MODEL
    ) IN DATABASE AUTOLDB
    INTERNALNAME STOCK
    SOURCE(AUTODB.STOCK DATA)
    CCSID 'Cp1047';

CREATE TABLE STOCSALE (
    FOREIGN KEY REFERENCES STOCK
    ) IN DATABASE AUTOLDB
    INTERNALNAME STOCSALE
    SOURCE(AUTODB.STOCSALE DATA, AUTODB.MODEL KEY)
    CCSID 'Cp1047';

CREATE TABLE SALESPER (
    FOREIGN KEY REFERENCES DEALER
    ) IN DATABASE AUTOLDB
    INTERNALNAME SALESPER
    SOURCE(AUTODB.SALESPER DATA, EMPDB2.EMPL DATA)
    CCSID 'Cp1047';

CREATE TABLE SALESINF (
    FOREIGN KEY REFERENCES SALESPER
    ) IN DATABASE AUTOLDB
    INTERNALNAME SALESINF
    SOURCE(AUTODB.SALESINF DATA)
    CCSID 'Cp1047';

CREATE TABLE EMPLINFO (
    FOREIGN KEY REFERENCES SALESPER
    ) IN DATABASE AUTOLDB
    INTERNALNAME EMPLINFO
    SOURCE(EMPDB2.EMPLINFO DATA)
    CCSID 'Cp1047';


COMMIT;