CREATE DATABASE DHDHOS1 ACCESS HISAM
    VERSION '07/15/2026.16'
    PASSWDNO
    DATXEXITNO
    DATA CAPTURE NONE CCSID 'Cp1047';

CREATE TABLESPACE DHDHOS1 IN DHDHOS1
    RECORD(31,31)
    SIZE PRIMARY 2048 SIZE SECONDARY 2048
    OVERFLOW(DHDHOS1O);

CREATE TABLE HOSPITAL (
    HOSPCODE CHAR(11)
        START 1
        TYPE C
        INTERNALNAME HOSPCODE
        PRIMARY KEY
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    HOSPNAME CHAR(20)
        START 12
        TYPE C
        INTERNALNAME HOSPNAME
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047'
    ) IN DATABASE DHDHOS1
    INTERNALNAME HOSPITAL
    MAXBYTES 31
    INSERT LOGICAL DELETE LOGICAL REPLACE LOGICAL
    AMBIGUOUS INSERT LAST
    CCSID 'Cp1047';

CREATE TABLE WARD (
    WARDNO CHAR(4)
        START 1
        TYPE C
        INTERNALNAME WARDNO
        PRIMARY KEY
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    WARDNAME CHAR(16)
        START 5
        TYPE C
        INTERNALNAME WARDNAME
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    HOSPCODE CHAR(11)
        START 21
        TYPE C
        INTERNALNAME HOSPCODE
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    FOREIGN KEY REFERENCES HOSPITAL
    ) IN DATABASE DHDHOS1
    INTERNALNAME WARD
    MAXBYTES 31
    INSERT LOGICAL DELETE LOGICAL REPLACE LOGICAL
    AMBIGUOUS INSERT LAST
    CCSID 'Cp1047';

CREATE TABLE PATIENT (
    PATNO CHAR(4)
        START 1
        TYPE C
        INTERNALNAME PATNO
        PRIMARY KEY
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    PATNAME CHAR(20)
        START 5
        TYPE C
        INTERNALNAME PATNAME
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    WARDNO CHAR(4)
        START 25
        TYPE C
        INTERNALNAME WARDNO
        INTERNAL TYPECONVERTER CHAR
        CCSID 'Cp1047',
    FOREIGN KEY REFERENCES WARD
    ) IN DATABASE DHDHOS1
    INTERNALNAME PATIENT
    MAXBYTES 28
    INSERT LOGICAL DELETE LOGICAL REPLACE LOGICAL
    AMBIGUOUS INSERT LAST
    CCSID 'Cp1047';


COMMIT;