CREATE PROGRAMVIEW DFSSAMT4 (
    CREATE SCHEMA DBPCB01 USING DFSSAMT4
        AS DBPCB01 (
            CREATE SENSEGVIEW PARTROOT
        )
        PROCOPT 'AP' LISTYES
        POSSNGL SBCOND
) CMPATYES GSROLBOKNO OLICYES LOCKMAX 0 IOASIZE 600 SSASIZE 840
    LANGASSEM;

COMMIT DDL;
