CREATE PROGRAMVIEW DHHOSPSB (
    CREATE SCHEMA PCB01 USING DHHOSPSB
        AS PCB01 (
            CREATE SENSEGVIEW HOSPITAL,
            CREATE SENSEGVIEW PATIENT,
            CREATE SENSEGVIEW WARD
        )
        PROCOPT 'AP' LISTYES
        POSSNGL SBCOND
) CMPATYES GSROLBOKNO OLICYES LOCKMAX 0 IOASIZE 600 SSASIZE 840
    LANGASSEM;

COMMIT DDL;
